// Grammar N5 Seed Data — 20 core grammar points
export const grammarData = [
  {
    title: "〜です (desu)",
    level: "N5",
    meaning: "Là... / Đây là... — Trợ động từ kính ngữ kết thúc câu khẳng định",
    structure: "[Danh từ / Tính từ -i] + です",
    commonMistakes: "Không dùng です sau động từ thông thường. Đừng nói「食べますです」— sai！Chỉ nói「食べます」。",
    examples: [
      { japanese: "私は学生です。", romaji: "Watashi wa gakusei desu.", meaning: "Tôi là học sinh." },
      { japanese: "これはペンです。", romaji: "Kore wa pen desu.", meaning: "Đây là cây bút." },
      { japanese: "天気はいいです。", romaji: "Tenki wa ii desu.", meaning: "Thời tiết tốt." },
    ],
  },
  {
    title: "〜ではありません / じゃないです",
    level: "N5",
    meaning: "Không phải là... — Phủ định lịch sự của です",
    structure: "[Danh từ] + ではありません (trang trọng) / じゃないです (thường ngày)",
    commonMistakes: "じゃないです là dạng thông dụng hơn. ではありません thường dùng trong văn viết hay tình huống formal.",
    examples: [
      { japanese: "私は先生ではありません。", romaji: "Watashi wa sensei dewa arimasen.", meaning: "Tôi không phải là giáo viên." },
      { japanese: "これはほんじゃないです。", romaji: "Kore wa hon ja nai desu.", meaning: "Đây không phải là cuốn sách." },
    ],
  },
  {
    title: "〜は (wa) — Trợ từ chủ đề",
    level: "N5",
    meaning: "Trợ từ đánh dấu chủ đề câu nói. Dịch: 'Về... thì / Còn... thì'",
    structure: "[Chủ đề] + は + [Bình luận về chủ đề]",
    commonMistakes: "は ≠ が. は đánh dấu chủ đề/bối cảnh (topic), が đánh dấu chủ ngữ thực sự (subject). Trong câu hỏi, thường dùng が để hỏi 'ai/cái gì'.",
    examples: [
      { japanese: "私は日本語を勉強しています。", romaji: "Watashi wa nihongo wo benkyou shite imasu.", meaning: "Tôi đang học tiếng Nhật." },
      { japanese: "東京は大きいです。", romaji: "Tōkyō wa ōkii desu.", meaning: "Tokyo thì to lớn." },
      { japanese: "コーヒーは飲みますが、お茶は飲みません。", romaji: "Koohii wa nomimasu ga, ocha wa nomimasen.", meaning: "Cà phê thì uống, nhưng trà thì không uống." },
    ],
  },
  {
    title: "〜が (ga) — Trợ từ chủ ngữ",
    level: "N5",
    meaning: "Trợ từ đánh dấu chủ ngữ câu — ai/cái gì thực sự thực hiện hành động",
    structure: "[Chủ ngữ] + が + [Vị ngữ]",
    commonMistakes: "Dùng が sau từ hỏi (誰/何/どれ), sau câu phụ (before が/けど), và khi muốn nhấn mạnh chủ ngữ.",
    examples: [
      { japanese: "誰が来ましたか？", romaji: "Dare ga kimashita ka?", meaning: "Ai đã đến?" },
      { japanese: "猫が魚を食べています。", romaji: "Neko ga sakana wo tabete imasu.", meaning: "Con mèo đang ăn cá." },
      { japanese: "日本語が好きです。", romaji: "Nihongo ga suki desu.", meaning: "Tôi thích tiếng Nhật. (が với tính từ cảm xúc)", },
    ],
  },
  {
    title: "〜を (wo) — Trợ từ tân ngữ trực tiếp",
    level: "N5",
    meaning: "Đánh dấu tân ngữ trực tiếp (direct object) — đối tượng bị tác động bởi hành động",
    structure: "[Tân ngữ] + を + [Động từ chuyển tiếp]",
    commonMistakes: "Chỉ dùng với động từ chuyển tiếp (có tân ngữ). Không dùng với động từ vô tiếp (như 行く, 来る, いる).",
    examples: [
      { japanese: "パンを食べます。", romaji: "Pan wo tabemasu.", meaning: "Tôi ăn bánh mì." },
      { japanese: "音楽を聞きます。", romaji: "Ongaku wo kikimasu.", meaning: "Tôi nghe nhạc." },
      { japanese: "日本語を勉強しています。", romaji: "Nihongo wo benkyou shite imasu.", meaning: "Tôi đang học tiếng Nhật." },
    ],
  },
  {
    title: "〜に (ni) — Trợ từ đích / thời gian",
    level: "N5",
    meaning: "Đích đến, nơi tồn tại, hoặc thời điểm cụ thể. Đa năng nhất trong các trợ từ!",
    structure: "[Địa điểm/Thời gian] + に + [Động từ]",
    commonMistakes: "に vs で: に dùng cho đích đến và tồn tại (います/あります). で dùng cho nơi diễn ra hành động. 学校に行く (đến trường) vs 学校で勉強する (học ở trường).",
    examples: [
      { japanese: "学校に行きます。", romaji: "Gakkō ni ikimasu.", meaning: "Tôi đi đến trường." },
      { japanese: "机の上に本があります。", romaji: "Tsukue no ue ni hon ga arimasu.", meaning: "Có sách ở trên bàn." },
      { japanese: "七時に起きます。", romaji: "Shichi-ji ni okimasu.", meaning: "Tôi thức dậy lúc 7 giờ." },
    ],
  },
  {
    title: "〜で (de) — Trợ từ địa điểm hành động / phương tiện",
    level: "N5",
    meaning: "Nơi diễn ra hành động, phương tiện/công cụ được dùng, nguyên nhân",
    structure: "[Địa điểm/Phương tiện] + で + [Hành động]",
    commonMistakes: "で vs に: で = nơi hành động xảy ra. に = nơi đến/nơi tồn tại.",
    examples: [
      { japanese: "図書館で勉強します。", romaji: "Toshokan de benkyou shimasu.", meaning: "Tôi học ở thư viện." },
      { japanese: "電車で会社に行きます。", romaji: "Densha de kaisha ni ikimasu.", meaning: "Tôi đi làm bằng tàu điện." },
      { japanese: "日本語で話してください。", romaji: "Nihongo de hanashite kudasai.", meaning: "Hãy nói bằng tiếng Nhật." },
    ],
  },
  {
    title: "〜てください (te kudasai)",
    level: "N5",
    meaning: "Làm ơn hãy... — Yêu cầu lịch sự",
    structure: "[Te-form của động từ] + ください",
    commonMistakes: "Đây là câu yêu cầu lịch sự, không phải mệnh lệnh thô. Với cấp trên, thêm していただけませんか？ lịch sự hơn.",
    examples: [
      { japanese: "ゆっくり話してください。", romaji: "Yukkuri hanashite kudasai.", meaning: "Làm ơn nói chậm thôi." },
      { japanese: "ここに名前を書いてください。", romaji: "Koko ni namae wo kaite kudasai.", meaning: "Làm ơn viết tên ở đây." },
      { japanese: "ちょっと待ってください。", romaji: "Chotto matte kudasai.", meaning: "Làm ơn đợi một chút." },
    ],
  },
  {
    title: "〜ています (te imasu)",
    level: "N5",
    meaning: "Đang... (tiếp diễn) / Là trạng thái hiện tại (kết quả của hành động đã xảy ra)",
    structure: "[Te-form] + います",
    commonMistakes: "います có 2 nghĩa: (1) đang làm gì đó [hành động tiếp diễn], (2) ở trạng thái nào đó [kết quả]. 結婚しています = đang ở trạng thái đã kết hôn (không phải 'đang kết hôn').",
    examples: [
      { japanese: "今、本を読んでいます。", romaji: "Ima, hon wo yonde imasu.", meaning: "Bây giờ tôi đang đọc sách." },
      { japanese: "結婚しています。", romaji: "Kekkon shite imasu.", meaning: "Tôi đã (đang) kết hôn." },
      { japanese: "田中さんはどこにいますか？— 図書館にいます。", romaji: "Tanaka-san wa doko ni imasu ka? — Toshokan ni imasu.", meaning: "Anh Tanaka đang ở đâu? — Ở thư viện." },
    ],
  },
  {
    title: "〜たいです (tai desu)",
    level: "N5",
    meaning: "Tôi muốn... — Diễn đạt mong muốn của người nói",
    structure: "[V-stem (masu-form bỏ ます)] + たいです",
    commonMistakes: "Chỉ dùng cho ngôi thứ nhất (tôi muốn). Không dùng để nói 'anh ấy muốn'. Với người khác: 〜たがっています.",
    examples: [
      { japanese: "日本へ行きたいです。", romaji: "Nihon e ikitai desu.", meaning: "Tôi muốn đến Nhật." },
      { japanese: "寿司が食べたいです。", romaji: "Sushi ga tabetai desu.", meaning: "Tôi muốn ăn sushi." },
      { japanese: "日本語が上手になりたいです。", romaji: "Nihongo ga jōzu ni naritai desu.", meaning: "Tôi muốn trở nên giỏi tiếng Nhật." },
    ],
  },
  {
    title: "〜てもいいですか？ (te mo ii desu ka)",
    level: "N5",
    meaning: "Tôi có thể...không? — Xin phép làm gì đó",
    structure: "[Te-form] + もいいですか？",
    commonMistakes: "Trả lời đồng ý: はい、どうぞ / ええ、もちろん. Từ chối lịch sự: ちょっと... (rồi dừng lại, hàm ý không).",
    examples: [
      { japanese: "ここに座ってもいいですか？", romaji: "Koko ni suwatte mo ii desu ka?", meaning: "Tôi có thể ngồi đây không?" },
      { japanese: "写真を撮ってもいいですか？", romaji: "Shashin wo totte mo ii desu ka?", meaning: "Tôi có thể chụp ảnh không?" },
      { japanese: "トイレを使ってもいいですか？", romaji: "Toire wo tsukatte mo ii desu ka?", meaning: "Tôi có thể dùng nhà vệ sinh không?" },
    ],
  },
  {
    title: "〜てはいけません (te wa ikemasen)",
    level: "N5",
    meaning: "Không được phép... — Cấm chỉ, quy định",
    structure: "[Te-form] + はいけません",
    commonMistakes: "Mạnh hơn 〜ないでください. Dùng trong quy tắc, luật lệ, quy định. Không dùng với người thân thân thiết (quá cứng nhắc).",
    examples: [
      { japanese: "ここでたばこを吸ってはいけません。", romaji: "Koko de tabako wo sutte wa ikemasen.", meaning: "Không được hút thuốc ở đây." },
      { japanese: "試験中に辞書を使ってはいけません。", romaji: "Shiken-chū ni jisho wo tsukatte wa ikemasen.", meaning: "Trong khi thi không được dùng từ điển." },
    ],
  },
  {
    title: "〜から (kara) — Nguyên nhân",
    level: "N5",
    meaning: "Vì..., Nên... — Diễn đạt nguyên nhân/lý do",
    structure: "[Nguyên nhân] + から + [Kết quả]",
    commonMistakes: "から (nguyên nhân) vs ので (lý do lịch sự). ので nghe lịch sự và nhẹ nhàng hơn から, thường dùng khi xin phép hay giải thích với cấp trên.",
    examples: [
      { japanese: "雨が降っているから、傘を持って行きます。", romaji: "Ame ga futte iru kara, kasa wo motte ikimasu.", meaning: "Vì trời mưa nên tôi mang ô theo." },
      { japanese: "日本語が好きだから、毎日勉強します。", romaji: "Nihongo ga suki da kara, mainichi benkyou shimasu.", meaning: "Vì thích tiếng Nhật nên tôi học mỗi ngày." },
    ],
  },
  {
    title: "〜より〜のほうが (yori ~ no hou ga)",
    level: "N5",
    meaning: "... hơn ... — So sánh hơn kém",
    structure: "[A] より [B] のほうが [Tính từ] です",
    commonMistakes: "Nhớ: B nằm ở vị trí 'hơn'. AよりBのほうが好き = thích B hơn A. Dễ nhầm thứ tự!",
    examples: [
      { japanese: "東京より大阪のほうが好きです。", romaji: "Tōkyō yori Ōsaka no hō ga suki desu.", meaning: "Tôi thích Osaka hơn Tokyo." },
      { japanese: "バスより電車のほうが速いです。", romaji: "Basu yori densha no hō ga hayai desu.", meaning: "Tàu điện nhanh hơn xe buýt." },
      { japanese: "AとBとどちらのほうが好きですか？", romaji: "A to B to dochira no hō ga suki desu ka?", meaning: "Giữa A và B, bạn thích cái nào hơn?" },
    ],
  },
  {
    title: "〜ましょう (mashou) — Đề nghị cùng làm",
    level: "N5",
    meaning: "Hãy cùng... / Chúng ta cùng... — Lời mời/đề nghị làm cùng nhau",
    structure: "[V-stem] + ましょう",
    commonMistakes: "ましょう mạnh hơn ませんか (nhẹ nhàng, hỏi ý kiến). ましょう gần như đã quyết định, ませんか chỉ là gợi ý.",
    examples: [
      { japanese: "一緒に昼ごはんを食べましょう！", romaji: "Issho ni hirugohan wo tabemashou!", meaning: "Hãy cùng ăn trưa đi！" },
      { japanese: "行きましょう！", romaji: "Ikimashou!", meaning: "Đi thôi！" },
      { japanese: "始めましょうか？", romaji: "Hajimemashou ka?", meaning: "Chúng ta bắt đầu nhé?" },
    ],
  },
  {
    title: "〜ませんか (masen ka) — Mời/Gợi ý lịch sự",
    level: "N5",
    meaning: "Bạn có muốn... không? — Lời mời lịch sự",
    structure: "[V-stem] + ませんか",
    commonMistakes: "Lịch sự và nhẹ nhàng hơn ましょう. Người được hỏi hoàn toàn có quyền từ chối mà không thấy ngại.",
    examples: [
      { japanese: "一緒に映画を見ませんか？", romaji: "Issho ni eiga wo mimasen ka?", meaning: "Bạn có muốn cùng xem phim không?" },
      { japanese: "お茶でも飲みませんか？", romaji: "Ocha demo nomimasen ka?", meaning: "Uống trà gì đó không?" },
    ],
  },
  {
    title: "〜ないでください (naide kudasai)",
    level: "N5",
    meaning: "Làm ơn đừng... — Yêu cầu không làm gì đó",
    structure: "[V-negative stem (ない form)] + でください",
    commonMistakes: "Nhẹ nhàng hơn 〜てはいけません. Dùng khi nhắn nhủ ai đó, không phải quy định cứng nhắc.",
    examples: [
      { japanese: "ここで写真を撮らないでください。", romaji: "Koko de shashin wo toranaide kudasai.", meaning: "Làm ơn đừng chụp ảnh ở đây." },
      { japanese: "忘れないでください！", romaji: "Wasurenaide kudasai!", meaning: "Đừng quên nhé！" },
    ],
  },
  {
    title: "〜てから (te kara) — Sau khi...",
    level: "N5",
    meaning: "Sau khi làm X thì làm Y — Thứ tự hành động",
    structure: "[Te-form V1] + から + [V2]",
    commonMistakes: "てから nhấn mạnh thứ tự: X XONG RỒI mới Y. Khác với あとで (sau đó) — あとで không bắt buộc thứ tự chặt chẽ.",
    examples: [
      { japanese: "手を洗ってから、ご飯を食べます。", romaji: "Te wo aratte kara, gohan wo tabemasu.", meaning: "Sau khi rửa tay thì ăn cơm." },
      { japanese: "宿題をしてから、遊びます。", romaji: "Shukudai wo shite kara, asobimasu.", meaning: "Làm bài tập xong rồi mới chơi." },
    ],
  },
  {
    title: "〜のが好き / 嫌い (no ga suki / kirai)",
    level: "N5",
    meaning: "Thích/Ghét làm gì đó — Danh từ hóa động từ bằng の",
    structure: "[Động từ thể thường] + のが + 好き/嫌い/得意/下手 + です",
    commonMistakes: "の ở đây danh từ hóa cả cụm động từ. 泳ぐのが好き (thích bơi) — の thay thế cho 'việc bơi'.",
    examples: [
      { japanese: "日本語を話すのが好きです。", romaji: "Nihongo wo hanasu no ga suki desu.", meaning: "Tôi thích nói tiếng Nhật." },
      { japanese: "料理をするのが得意です。", romaji: "Ryōri wo suru no ga tokui desu.", meaning: "Tôi giỏi nấu ăn." },
      { japanese: "早起きするのが嫌いです。", romaji: "Hayaoki suru no ga kirai desu.", meaning: "Tôi ghét dậy sớm." },
    ],
  },
  {
    title: "〜もう / まだ (mou / mada)",
    level: "N5",
    meaning: "もう = Rồi / Đã (affirmative) / Không còn... nữa (negative). まだ = Vẫn còn / Chưa",
    structure: "もう + [Khẳng định] / もう〜ない = Không còn. まだ + [Khẳng định] = Vẫn còn / まだ + [Phủ định] = Chưa",
    commonMistakes: "もう食べました = Đã ăn rồi. もう食べません = Không ăn nữa. まだ食べます = Vẫn còn đang ăn. まだ食べていません = Chưa ăn.",
    examples: [
      { japanese: "もう宿題をしました。", romaji: "Mou shukudai wo shimashita.", meaning: "Đã làm bài tập rồi." },
      { japanese: "まだ日本語を勉強しています。", romaji: "Mada nihongo wo benkyou shite imasu.", meaning: "Vẫn đang học tiếng Nhật." },
      { japanese: "まだ食べていません。", romaji: "Mada tabete imasen.", meaning: "Chưa ăn." },
    ],
  },
  {
    title: "〜なければなりません (nakereba narimasen)",
    level: "N5",
    meaning: "Phải làm gì đó — Diễn tả nghĩa vụ hoặc sự cần thiết bắt buộc",
    structure: "[V-nai (bỏ い)] + ければなりません",
    commonMistakes: "Dạng thân mật hàng ngày: 〜なきゃ (nakya) hoặc 〜なくちゃ (nakucha). Chú ý không bỏ sót ければ.",
    examples: [
      { japanese: "薬を飲まなければなりません。", romaji: "Kusuri wo nomanakereba narimasen.", meaning: "Tôi phải uống thuốc." },
      { japanese: "明日早く起きなければなりません。", romaji: "Ashita hayaku okinakereba narimasen.", meaning: "Ngày mai tôi phải dậy sớm." },
    ],
  },
  {
    title: "〜ことができます (koto ga dekimasu)",
    level: "N5",
    meaning: "Có thể làm gì đó — Diễn đạt năng lực hoặc tính khả thi",
    structure: "[V thể từ điển (Jishokei)] + ことができます",
    commonMistakes: "Trước ことができます LUÔN là động từ thể từ điển (nguyên mẫu), không dùng thể ます.",
    examples: [
      { japanese: "日本語を話すことができます。", romaji: "Nihongo wo hanasu koto ga dekimasu.", meaning: "Tôi có thể nói tiếng Nhật." },
      { japanese: "ここでカードを使うことができますか？", romaji: "Koko de kaado wo tsukau koto ga dekimasu ka?", meaning: "Ở đây có thể thanh toán bằng thẻ được không?" },
    ],
  },
  {
    title: "〜たことがあります (ta koto ga arimasu)",
    level: "N5",
    meaning: "Đã từng làm gì đó — Kể về kinh nghiệm trải nghiệm trong quá khứ",
    structure: "[V-ta (thể quá khứ ngắn)] + ことがあります",
    commonMistakes: "Chỉ dùng để nói về kinh nghiệm một vài lần trong đời. Không dùng cho hành động hàng ngày như 'hôm qua tôi đã ăn cơm'.",
    examples: [
      { japanese: "日本へ行ったことがあります。", romaji: "Nihon e itta koto ga arimasu.", meaning: "Tôi đã từng đi Nhật Bản." },
      { japanese: "富士山に登ったことがありますか？", romaji: "Fujisan ni nobotta koto ga arimasu ka?", meaning: "Bạn đã từng leo núi Phú Sĩ chưa?" },
    ],
  },
  {
    title: "〜たり〜たりする (tari ... tari suru)",
    level: "N5",
    meaning: "Lúc thì làm A, lúc thì làm B — Liệt kê một vài hành động tiêu biểu",
    structure: "[V1-ta] + り、[V2-ta] + り します / しました",
    commonMistakes: "Phải kết thúc bằng します (hiện tại/tương lai) hoặc しました (quá khứ). Không được thiếu từ kết thúc.",
    examples: [
      { japanese: "休みの日は本を読んだり、音楽を聞いたりします。", romaji: "Yasumi no hi wa hon wo yondari, ongaku wo kiitari shimasu.", meaning: "Vào ngày nghỉ tôi lúc thì đọc sách, lúc thì nghe nhạc." },
      { japanese: "昨日は買い物をしたり、映画を見たりしました。", romaji: "Kinou wa kaimono wo shitari, eiga wo mitari shimashita.", meaning: "Hôm qua tôi đã đi mua sắm rồi xem phim." },
    ],
  },
  {
    title: "〜つもりです (tsumori desu)",
    level: "N5",
    meaning: "Dự định làm gì đó — Thể hiện ý định hoặc kế hoạch cá nhân",
    structure: "[V thể từ điển] + つもりです (Dự định làm) / [V-nai] + つもりです (Dự định không làm)",
    commonMistakes: "Chỉ dùng cho dự định của bản thân (ngôi thứ nhất) hoặc hỏi người nghe. Không dùng tùy tiện để phán đoán người khác.",
    examples: [
      { japanese: "来年日本へ旅行するつもりです。", romaji: "Rainen Nihon e ryokou suru tsumori desu.", meaning: "Tôi dự định sang năm sẽ đi du lịch Nhật Bản." },
      { japanese: "タバコをやめるつもりです。", romaji: "Tabako wo yameru tsumori desu.", meaning: "Tôi có ý định sẽ bỏ hút thuốc lá." },
    ],
  },
  {
    title: "〜ほうがいいです (hou ga ii desu)",
    level: "N5",
    meaning: "Nên làm gì / Không nên làm gì — Đưa ra lời khuyên nhủ lịch sự",
    structure: "[V-ta] + ほうがいいです (Nên làm) / [V-nai] + ほうがいいです (Không nên làm)",
    commonMistakes: "Khuyên nên làm thì dùng thể Ta: 食べたほうがいい (không dùng 食べる). Khuyên không nên thì dùng thể Nai: 行かないほうがいい.",
    examples: [
      { japanese: "病院へ行ったほうがいいですよ。", romaji: "Byouin e itta hou ga ii desu yo.", meaning: "Bạn nên đi bệnh viện khám thì hơn đấy." },
      { japanese: "無理をしないほうがいいです。", romaji: "Muri wo shinai hou ga ii desu.", meaning: "Bạn không nên làm việc quá sức." },
    ],
  },
  {
    title: "〜より〜のほうが (yori ... no hou ga)",
    level: "N5",
    meaning: "B thì [tính từ] hơn A — Mẫu câu so sánh hơn trong tiếng Nhật",
    structure: "[A] より [B] のほうが [Tính từ] です",
    commonMistakes: "Chủ thể được khen hơn sẽ đi liền trước のほうが. Dễ nhầm vị trí A và B.",
    examples: [
      { japanese: "電車より新幹線のほうが速いです。", romaji: "Densha yori Shinkansen no hou ga hayai desu.", meaning: "Tàu Shinkansen thì nhanh hơn tàu điện thường." },
      { japanese: "夏より冬のほうが好きです。", romaji: "Natsu yori fuyu no hou ga suki desu.", meaning: "Tôi thích mùa đông hơn mùa hè." },
    ],
  },
  {
    title: "〜の中で〜が一番 (no naka de ... ga ichiban)",
    level: "N5",
    meaning: "Trong số... thì... là nhất — Mẫu câu so sánh nhất",
    structure: "[Phạm vi] の中で [Chủ thể] が 一番 [Tính từ] です",
    commonMistakes: "Hỏi: [Phạm vi] の中で [なに/だれ/どこ/いつ] が一番〜ですか？ Trả lời bằng が 一番.",
    examples: [
      { japanese: "日本料理の中で寿司が一番好きです。", romaji: "Nihon ryouri no naka de sushi ga ichiban suki desu.", meaning: "Trong các món ăn Nhật, tôi thích nhất là sushi." },
      { japanese: "スポーツの中で何が一番面白いですか？", romaji: "Supootsu no naka de nani ga ichiban omoshiroi desu ka?", meaning: "Trong các môn thể thao, môn nào thú vị nhất?" },
    ],
  },
  {
    title: "〜まえに (mae ni) — Trước khi...",
    level: "N5",
    meaning: "Trước khi làm việc A thì làm B — Mốc thời gian trước",
    structure: "[V thể từ điển] + まえに / [Danh từ] + のまえに",
    commonMistakes: "Dù hành động xảy ra trong quá khứ thì động từ trước まえに VẪN LUÔN ở thể từ điển: 寝るまえに (trước khi ngủ), không chia quá khứ.",
    examples: [
      { japanese: "寝るまえに、本を読みます。", romaji: "Neru mae ni, hon wo yomimasu.", meaning: "Trước khi đi ngủ, tôi đọc sách." },
      { japanese: "食事のまえに、手を洗います。", romaji: "Shokuji no mae ni, te wo arawimasu.", meaning: "Trước bữa ăn, tôi rửa sạch tay." },
    ],
  },
  {
    title: "〜あとで (ato de) — Sau khi...",
    level: "N5",
    meaning: "Sau khi làm A thì làm B — Mốc thời gian sau",
    structure: "[V-ta] + あとで / [Danh từ] + のあとで",
    commonMistakes: "Trước あとで luôn là động từ thể Ta (quá khứ) hoặc Danh từ + の.",
    examples: [
      { japanese: "ご飯を食べたあとで、散歩します。", romaji: "Gohan wo tabeta ato de, sanpo shimasu.", meaning: "Sau khi ăn cơm xong, tôi đi dạo bộ." },
      { japanese: "仕事のあとで、飲みに行きましょう。", romaji: "Shigoto no ato de, nomi ni ikimashou.", meaning: "Sau giờ làm việc, chúng mình đi uống nhé." },
    ],
  },
  {
    title: "〜ながら (nagara) — Vừa... vừa...",
    level: "N5",
    meaning: "Vừa làm hành động A vừa làm hành động B cùng một lúc",
    structure: "[V1-masu (bỏ ます)] + ながら + [V2]",
    commonMistakes: "Hành động chính nằm ở V2 (hành động phía sau). V1 là hành động phụ kèm theo.",
    examples: [
      { japanese: "音楽を聞きながら、勉強します。", romaji: "Ongaku wo kikinagara, benkyou shimasu.", meaning: "Tôi vừa nghe nhạc vừa học bài." },
      { japanese: "歩きながら、スマホを見ないでください。", romaji: "Arukinagara, sumaho wo minaide kudasai.", meaning: "Xin đừng vừa đi bộ vừa nhìn điện thoại." },
    ],
  },
  {
    title: "〜すぎます (sugimasu) — Quá mức",
    level: "N5",
    meaning: "Quá mức, quá đáng — Diễn tả sự vượt quá giới hạn bình thường",
    structure: "[V-masu (bỏ ます)] + すぎます / [Tính từ -i (bỏ い)] + すぎます / [Tính từ -na] + すぎます",
    commonMistakes: "Tính từ đuôi い phải bỏ い (高すぎる, không phải 高いすぎる). Thường mang ý nghĩa tiêu cực.",
    examples: [
      { japanese: "昨日食べすぎました。", romaji: "Kinou tabesugimashita.", meaning: "Hôm qua tôi ăn nhiều quá mức." },
      { japanese: "この問題は難しすぎます。", romaji: "Kono mondai wa muzukashisugimasu.", meaning: "Câu hỏi này khó quá." },
    ],
  },
  {
    title: "〜くなります / になります (narimasu)",
    level: "N5",
    meaning: "Trở nên, trở thành — Diễn đạt sự biến đổi trạng thái",
    structure: "[Tính từ -i (bỏ い)] + くなります / [Tính từ -na / Danh từ] + になります",
    commonMistakes: "Tính từ -i thì dùng く, Tính từ -na và Danh từ thì dùng に.",
    examples: [
      { japanese: "寒くなりましたね。", romaji: "Samuku narimashita ne.", meaning: "Trời đã trở nên lạnh rồi nhỉ." },
      { japanese: "日本語が上手になりました。", romaji: "Nihongo ga jouzu ni narimashita.", meaning: "Tiếng Nhật của bạn đã giỏi lên rồi." },
    ],
  },
  {
    title: "〜から / 〜ので (kara / node) — Vì... nên...",
    level: "N5",
    meaning: "Chỉ nguyên nhân, lý do — Vì lý do này nên dẫn tới kết quả kia",
    structure: "[Mệnh đề nguyên nhân] + から / ので + [Mệnh đề kết quả]",
    commonMistakes: "から mang tính chủ quan, cảm xúc cá nhân. ので mang tính khách quan, lịch sự và trang trọng hơn.",
    examples: [
      { japanese: "時間がありませんから、タクシーで行きます。", romaji: "Jikan ga arimasen kara, takushii de ikimasu.", meaning: "Vì không có thời gian nên tôi sẽ đi bằng taxi." },
      { japanese: "雨が降っているので、傘を持って行きます。", romaji: "Ame ga futte iru node, kasa wo motte ikimasu.", meaning: "Vì trời đang mưa nên tôi mang theo ô dù." },
    ],
  },
  {
    title: "〜でしょう / だろう (deshou / darou)",
    level: "N5",
    meaning: "Có lẽ là... / Chắc là... — Phỏng đoán nhẹ nhàng hoặc tìm kiếm sự đồng tình",
    structure: "[Thể thông thường] + でしょう (lịch sự) / だろう (thân mật)",
    commonMistakes: "Với Danh từ và Tính từ -na ở hiện tại khẳng định, bỏ だ trước でしょう.",
    examples: [
      { japanese: "明日はいい天気になるでしょう。", romaji: "Ashita wa ii tenki ni naru deshou.", meaning: "Ngày mai chắc là thời tiết sẽ đẹp." },
      { japanese: "北海道は今とても寒いでしょう。", romaji: "Hokkaidou wa ima totemo samui deshou.", meaning: "Hokkaido bây giờ chắc là lạnh lắm nhỉ." },
    ],
  },
];
