export interface SeedKanji {
  character: string;
  meaning: string;
  strokeCount: number;
  jlptLevel: string;
  readings: Array<{ reading: string; type: "ONYOMI" | "KUNYOMI" }>;
}

export interface SeedVocab {
  word: string;
  kana: string;
  kanji: string | null;
  romaji: string;
  meaning: string;
  partOfSpeech: string;
  jlptLevel: string;
  exampleJapanese: string;
  exampleRomaji: string;
  exampleMeaning: string;
}

export const KANJI_N5: SeedKanji[] = [
  // Số đếm
  { character: "一", meaning: "Một (Nhất)", strokeCount: 1, jlptLevel: "N5", readings: [{ reading: "イチ", type: "ONYOMI" }, { reading: "ひと・つ", type: "KUNYOMI" }] },
  { character: "二", meaning: "Hai (Nhị)", strokeCount: 2, jlptLevel: "N5", readings: [{ reading: "ニ", type: "ONYOMI" }, { reading: "ふた・つ", type: "KUNYOMI" }] },
  { character: "三", meaning: "Ba (Tam)", strokeCount: 3, jlptLevel: "N5", readings: [{ reading: "サン", type: "ONYOMI" }, { reading: "みっ・つ", type: "KUNYOMI" }] },
  { character: "四", meaning: "Bốn (Tứ)", strokeCount: 5, jlptLevel: "N5", readings: [{ reading: "シ", type: "ONYOMI" }, { reading: "よん", type: "KUNYOMI" }, { reading: "よっ・つ", type: "KUNYOMI" }] },
  { character: "五", meaning: "Năm (Ngũ)", strokeCount: 4, jlptLevel: "N5", readings: [{ reading: "ゴ", type: "ONYOMI" }, { reading: "いつ・つ", type: "KUNYOMI" }] },
  { character: "六", meaning: "Sáu (Lục)", strokeCount: 4, jlptLevel: "N5", readings: [{ reading: "ロク", type: "ONYOMI" }, { reading: "むっ・つ", type: "KUNYOMI" }] },
  { character: "七", meaning: "Bảy (Thất)", strokeCount: 2, jlptLevel: "N5", readings: [{ reading: "シチ", type: "ONYOMI" }, { reading: "なな・つ", type: "KUNYOMI" }] },
  { character: "八", meaning: "Tám (Bát)", strokeCount: 2, jlptLevel: "N5", readings: [{ reading: "ハチ", type: "ONYOMI" }, { reading: "やっ・つ", type: "KUNYOMI" }] },
  { character: "九", meaning: "Chín (Cửu)", strokeCount: 2, jlptLevel: "N5", readings: [{ reading: "キュウ", type: "ONYOMI" }, { reading: "ここの・つ", type: "KUNYOMI" }] },
  { character: "十", meaning: "Mười (Thập)", strokeCount: 2, jlptLevel: "N5", readings: [{ reading: "ジュウ", type: "ONYOMI" }, { reading: "とお", type: "KUNYOMI" }] },
  { character: "百", meaning: "Trăm (Bách)", strokeCount: 6, jlptLevel: "N5", readings: [{ reading: "ヒャク", type: "ONYOMI" }, { reading: "もも", type: "KUNYOMI" }] },
  { character: "千", meaning: "Nghìn (Thiên)", strokeCount: 3, jlptLevel: "N5", readings: [{ reading: "セン", type: "ONYOMI" }, { reading: "ち", type: "KUNYOMI" }] },
  { character: "万", meaning: "Vạn, Mười nghìn (Vạn)", strokeCount: 3, jlptLevel: "N5", readings: [{ reading: "マン", type: "ONYOMI" }, { reading: "バン", type: "ONYOMI" }] },
  { character: "円", meaning: "Đồng Yên, Tròn (Viên)", strokeCount: 4, jlptLevel: "N5", readings: [{ reading: "エン", type: "ONYOMI" }, { reading: "まる・い", type: "KUNYOMI" }] },

  // Thời gian & Thiên nhiên
  { character: "日", meaning: "Mặt trời, Ngày (Nhật)", strokeCount: 4, jlptLevel: "N5", readings: [{ reading: "ニチ", type: "ONYOMI" }, { reading: "ジツ", type: "ONYOMI" }, { reading: "ひ", type: "KUNYOMI" }, { reading: "び", type: "KUNYOMI" }] },
  { character: "月", meaning: "Mặt trăng, Tháng (Nguyệt)", strokeCount: 4, jlptLevel: "N5", readings: [{ reading: "ゲツ", type: "ONYOMI" }, { reading: "ガツ", type: "ONYOMI" }, { reading: "つき", type: "KUNYOMI" }] },
  { character: "火", meaning: "Lửa (Hỏa)", strokeCount: 4, jlptLevel: "N5", readings: [{ reading: "カ", type: "ONYOMI" }, { reading: "ひ", type: "KUNYOMI" }] },
  { character: "水", meaning: "Nước (Thủy)", strokeCount: 4, jlptLevel: "N5", readings: [{ reading: "スイ", type: "ONYOMI" }, { reading: "みず", type: "KUNYOMI" }] },
  { character: "木", meaning: "Cây gỗ (Mộc)", strokeCount: 4, jlptLevel: "N5", readings: [{ reading: "モク", type: "ONYOMI" }, { reading: "き", type: "KUNYOMI" }] },
  { character: "金", meaning: "Vàng, Tiền (Kim)", strokeCount: 8, jlptLevel: "N5", readings: [{ reading: "キン", type: "ONYOMI" }, { reading: "かね", type: "KUNYOMI" }] },
  { character: "土", meaning: "Đất (Thổ)", strokeCount: 3, jlptLevel: "N5", readings: [{ reading: "ド", type: "ONYOMI" }, { reading: "つち", type: "KUNYOMI" }] },
  { character: "年", meaning: "Năm (Niên)", strokeCount: 6, jlptLevel: "N5", readings: [{ reading: "ネン", type: "ONYOMI" }, { reading: "とし", type: "KUNYOMI" }] },
  { character: "時", meaning: "Giờ, Thời gian (Thời)", strokeCount: 10, jlptLevel: "N5", readings: [{ reading: "ジ", type: "ONYOMI" }, { reading: "とき", type: "KUNYOMI" }] },
  { character: "分", meaning: "Phút, Phần (Phân)", strokeCount: 4, jlptLevel: "N5", readings: [{ reading: "フン", type: "ONYOMI" }, { reading: "わ・ける", type: "KUNYOMI" }] },
  { character: "今", meaning: "Bây giờ (Kim)", strokeCount: 4, jlptLevel: "N5", readings: [{ reading: "コン", type: "ONYOMI" }, { reading: "いま", type: "KUNYOMI" }] },

  // Con người & Cuộc sống
  { character: "人", meaning: "Người (Nhân)", strokeCount: 2, jlptLevel: "N5", readings: [{ reading: "ジン", type: "ONYOMI" }, { reading: "ニン", type: "ONYOMI" }, { reading: "ひと", type: "KUNYOMI" }] },
  { character: "男", meaning: "Nam, Con trai (Nam)", strokeCount: 7, jlptLevel: "N5", readings: [{ reading: "ダン", type: "ONYOMI" }, { reading: "おとこ", type: "KUNYOMI" }] },
  { character: "女", meaning: "Nữ, Con gái (Nữ)", strokeCount: 3, jlptLevel: "N5", readings: [{ reading: "ジョ", type: "ONYOMI" }, { reading: "おんな", type: "KUNYOMI" }] },
  { character: "子", meaning: "Đứa trẻ (Tử)", strokeCount: 3, jlptLevel: "N5", readings: [{ reading: "シ", type: "ONYOMI" }, { reading: "こ", type: "KUNYOMI" }] },
  { character: "友", meaning: "Bạn bè (Hữu)", strokeCount: 4, jlptLevel: "N5", readings: [{ reading: "ユウ", type: "ONYOMI" }, { reading: "とも", type: "KUNYOMI" }] },
  { character: "父", meaning: "Bố, Cha (Phụ)", strokeCount: 4, jlptLevel: "N5", readings: [{ reading: "フ", type: "ONYOMI" }, { reading: "ちち", type: "KUNYOMI" }] },
  { character: "母", meaning: "Mẹ (Mẫu)", strokeCount: 5, jlptLevel: "N5", readings: [{ reading: "ボ", type: "ONYOMI" }, { reading: "はは", type: "KUNYOMI" }] },

  // Vị trí & Kích cỡ
  { character: "大", meaning: "Lớn, To (Đại)", strokeCount: 3, jlptLevel: "N5", readings: [{ reading: "ダイ", type: "ONYOMI" }, { reading: "おお・きい", type: "KUNYOMI" }] },
  { character: "中", meaning: "Ở giữa, Trong (Trung)", strokeCount: 4, jlptLevel: "N5", readings: [{ reading: "チュウ", type: "ONYOMI" }, { reading: "なか", type: "KUNYOMI" }] },
  { character: "小", meaning: "Nhỏ, Bé (Tiểu)", strokeCount: 3, jlptLevel: "N5", readings: [{ reading: "ショウ", type: "ONYOMI" }, { reading: "ちい・さい", type: "KUNYOMI" }] },
  { character: "上", meaning: "Ở trên (Thượng)", strokeCount: 3, jlptLevel: "N5", readings: [{ reading: "ジョウ", type: "ONYOMI" }, { reading: "うえ", type: "KUNYOMI" }] },
  { character: "下", meaning: "Ở dưới (Hạ)", strokeCount: 3, jlptLevel: "N5", readings: [{ reading: "カ", type: "ONYOMI" }, { reading: "した", type: "KUNYOMI" }] },
  { character: "左", meaning: "Bên trái (Tả)", strokeCount: 5, jlptLevel: "N5", readings: [{ reading: "サ", type: "ONYOMI" }, { reading: "ひだり", type: "KUNYOMI" }] },
  { character: "右", meaning: "Bên phải (Hữu)", strokeCount: 5, jlptLevel: "N5", readings: [{ reading: "ウ", type: "ONYOMI" }, { reading: "みぎ", type: "KUNYOMI" }] },
  { character: "前", meaning: "Phía trước (Tiền)", strokeCount: 9, jlptLevel: "N5", readings: [{ reading: "ゼン", type: "ONYOMI" }, { reading: "まえ", type: "KUNYOMI" }] },
  { character: "後", meaning: "Phía sau (Hậu)", strokeCount: 9, jlptLevel: "N5", readings: [{ reading: "ゴ", type: "ONYOMI" }, { reading: "あと", type: "KUNYOMI" }, { reading: "うし・ろ", type: "KUNYOMI" }] },

  // Động từ & Địa điểm
  { character: "行", meaning: "Đi (Hành)", strokeCount: 6, jlptLevel: "N5", readings: [{ reading: "コウ", type: "ONYOMI" }, { reading: "い・く", type: "KUNYOMI" }] },
  { character: "来", meaning: "Đến (Lai)", strokeCount: 7, jlptLevel: "N5", readings: [{ reading: "ライ", type: "ONYOMI" }, { reading: "く・る", type: "KUNYOMI" }] },
  { character: "見", meaning: "Nhìn, Xem (Kiến)", strokeCount: 7, jlptLevel: "N5", readings: [{ reading: "ケン", type: "ONYOMI" }, { reading: "み・る", type: "KUNYOMI" }] },
  { character: "聞", meaning: "Nghe, Hỏi (Văn)", strokeCount: 14, jlptLevel: "N5", readings: [{ reading: "ブン", type: "ONYOMI" }, { reading: "き・く", type: "KUNYOMI" }] },
  { character: "食", meaning: "Ăn (Thực)", strokeCount: 9, jlptLevel: "N5", readings: [{ reading: "ショク", type: "ONYOMI" }, { reading: "た・べる", type: "KUNYOMI" }] },
  { character: "飲", meaning: "Uống (Ẩm)", strokeCount: 12, jlptLevel: "N5", readings: [{ reading: "イン", type: "ONYOMI" }, { reading: "の・む", type: "KUNYOMI" }] },
  { character: "話", meaning: "Nói chuyện (Thoại)", strokeCount: 13, jlptLevel: "N5", readings: [{ reading: "ワ", type: "ONYOMI" }, { reading: "はな・す", type: "KUNYOMI" }] },
  { character: "買", meaning: "Mua (Mãi)", strokeCount: 12, jlptLevel: "N5", readings: [{ reading: "バイ", type: "ONYOMI" }, { reading: "か・う", type: "KUNYOMI" }] },
  { character: "読", meaning: "Đọc (Độc)", strokeCount: 14, jlptLevel: "N5", readings: [{ reading: "ドク", type: "ONYOMI" }, { reading: "よ・む", type: "KUNYOMI" }] },
  { character: "書", meaning: "Viết (Thư)", strokeCount: 10, jlptLevel: "N5", readings: [{ reading: "ショ", type: "ONYOMI" }, { reading: "か・く", type: "KUNYOMI" }] },
  { character: "山", meaning: "Núi (Sơn)", strokeCount: 3, jlptLevel: "N5", readings: [{ reading: "サン", type: "ONYOMI" }, { reading: "やま", type: "KUNYOMI" }] },
  { character: "川", meaning: "Sông (Xuyên)", strokeCount: 3, jlptLevel: "N5", readings: [{ reading: "セン", type: "ONYOMI" }, { reading: "かわ", type: "KUNYOMI" }] },
  { character: "本", meaning: "Sách, Gốc (Bản)", strokeCount: 5, jlptLevel: "N5", readings: [{ reading: "ホン", type: "ONYOMI" }, { reading: "もと", type: "KUNYOMI" }] },
];

export const VOCABULARY_N5: SeedVocab[] = [
  {
    word: "ありがとう",
    kana: "ありがとう",
    kanji: null,
    romaji: "arigatō",
    meaning: "Cảm ơn bạn",
    partOfSpeech: "expression",
    jlptLevel: "N5",
    exampleJapanese: "手伝ってくれてありがとう。",
    exampleRomaji: "Tetsudatte kurete arigatō.",
    exampleMeaning: "Cảm ơn bạn rất nhiều vì đã giúp đỡ tôi.",
  },
  {
    word: "こんにちは",
    kana: "こんにちは",
    kanji: null,
    romaji: "konnichiwa",
    meaning: "Xin chào (ban ngày)",
    partOfSpeech: "greeting",
    jlptLevel: "N5",
    exampleJapanese: "こんにちは！お元気ですか？",
    exampleRomaji: "Konnichiwa! Ogenki desu ka?",
    exampleMeaning: "Xin chào bạn! Hôm nay bạn có khỏe không?",
  },
  {
    word: "すみません",
    kana: "すみません",
    kanji: null,
    romaji: "sumimasen",
    meaning: "Xin lỗi / Cho tôi hỏi",
    partOfSpeech: "expression",
    jlptLevel: "N5",
    exampleJapanese: "すみません、駅はどこですか？",
    exampleRomaji: "Sumimasen, eki wa doko desu ka?",
    exampleMeaning: "Xin lỗi cho tôi hỏi, nhà ga ở đâu ạ?",
  },
  {
    word: "はい",
    kana: "はい",
    kanji: null,
    romaji: "hai",
    meaning: "Vâng, dạ, đúng vậy",
    partOfSpeech: "particle",
    jlptLevel: "N5",
    exampleJapanese: "はい、分かりました。",
    exampleRomaji: "Hai, wakarimashita.",
    exampleMeaning: "Vâng, tôi đã hiểu rồi ạ.",
  },
  {
    word: "食べる",
    kana: "たべる",
    kanji: "食べる",
    romaji: "taberu",
    meaning: "Ăn",
    partOfSpeech: "verb",
    jlptLevel: "N5",
    exampleJapanese: "美味しいラーメンを食べる。",
    exampleRomaji: "Oishii rāmen o taberu.",
    exampleMeaning: "Tôi ăn một tô mì Ramen thơm ngon.",
  },
  {
    word: "飲む",
    kana: "のむ",
    kanji: "飲む",
    romaji: "nomu",
    meaning: "Uống",
    partOfSpeech: "verb",
    jlptLevel: "N5",
    exampleJapanese: "冷たい水を飲む。",
    exampleRomaji: "Tsumetai mizu o nomu.",
    exampleMeaning: "Tôi uống một cốc nước mát lạnh.",
  },
  {
    word: "行く",
    kana: "いく",
    kanji: "行く",
    romaji: "iku",
    meaning: "Đi đến",
    partOfSpeech: "verb",
    jlptLevel: "N5",
    exampleJapanese: "新幹線で京都へ行く。",
    exampleRomaji: "Shinkansen de Kyōto e iku.",
    exampleMeaning: "Tôi đi đến cố đô Kyoto bằng tàu Shinkansen.",
  },
  {
    word: "来る",
    kana: "くる",
    kanji: "来る",
    romaji: "kuru",
    meaning: "Đến",
    partOfSpeech: "verb",
    jlptLevel: "N5",
    exampleJapanese: "友達が家に遊びに来る。",
    exampleRomaji: "Tomodachi ga ie ni asobi ni kuru.",
    exampleMeaning: "Bạn bè đến nhà tôi chơi.",
  },
  {
    word: "見る",
    kana: "みる",
    kanji: "見る",
    romaji: "miru",
    meaning: "Nhìn, xem",
    partOfSpeech: "verb",
    jlptLevel: "N5",
    exampleJapanese: "桜の花を見る。",
    exampleRomaji: "Sakura no hana o miru.",
    exampleMeaning: "Tôi ngắm hoa anh đào nở rộ.",
  },
  {
    word: "友達",
    kana: "ともだち",
    kanji: "友達",
    romaji: "tomodachi",
    meaning: "Bạn bè",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "私の親友は日本人です。",
    exampleRomaji: "Watashi no shin'yū wa Nihonjin desu.",
    exampleMeaning: "Bạn thân của tôi là người Nhật Bản.",
  },
  {
    word: "日本",
    kana: "にほん",
    kanji: "日本",
    romaji: "nihon",
    meaning: "Nhật Bản",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "いつか日本へ旅行したいです。",
    exampleRomaji: "Itsuka Nihon e ryokō shitai desu.",
    exampleMeaning: "Tôi muốn có dịp đi du lịch đất nước Nhật Bản.",
  },
  {
    word: "日本語",
    kana: "にほんご",
    kanji: "日本語",
    romaji: "nihongo",
    meaning: "Tiếng Nhật",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "毎日日本語を勉強します。",
    exampleRomaji: "Mainichi Nihongo o benkyō shimasu.",
    exampleMeaning: "Mỗi ngày tôi đều chăm chỉ học tiếng Nhật.",
  },
  {
    word: "先生",
    kana: "せんせい",
    kanji: "先生",
    romaji: "sensei",
    meaning: "Thầy giáo, cô giáo, bác sĩ",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "先生、質問があります。",
    exampleRomaji: "Sensei, shitsumon ga arimasu.",
    exampleMeaning: "Thưa thầy, em có một câu hỏi ạ.",
  },
  {
    word: "駅",
    kana: "えき",
    kanji: "駅",
    romaji: "eki",
    meaning: "Nhà ga xe lửa / tàu điện",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "駅の前で待ち合わせをしましょう。",
    exampleRomaji: "Eki no mae de machiawase o shimashō.",
    exampleMeaning: "Chúng ta hãy hẹn gặp nhau ở trước nhà ga nhé.",
  },
  {
    word: "本",
    kana: "ほん",
    kanji: "本",
    romaji: "hon",
    meaning: "Quyển sách",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "図書館で面白い本を読んだ。",
    exampleRomaji: "Toshokan de omoshiroi hon o yonda.",
    exampleMeaning: "Tôi đã đọc một cuốn sách rất thú vị ở thư viện.",
  },
  {
    word: "水",
    kana: "みず",
    kanji: "水",
    romaji: "mizu",
    meaning: "Nước (uống)",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "お水を一杯いただけますか？",
    exampleRomaji: "Omizu o ippai itadakemasu ka?",
    exampleMeaning: "Làm ơn cho tôi xin một ly nước lọc được không ạ?",
  },
  {
    word: "美味しい",
    kana: "おいしい",
    kanji: "美味しい",
    romaji: "oishii",
    meaning: "Ngon, thơm ngon",
    partOfSpeech: "adjective",
    jlptLevel: "N5",
    exampleJapanese: "日本の寿司は本当に美味しいです。",
    exampleRomaji: "Nihon no sushi wa hontō ni oishii desu.",
    exampleMeaning: "Món sushi của Nhật Bản thực sự rất ngon.",
  },
  {
    word: "大きい",
    kana: "おおきい",
    kanji: "大きい",
    romaji: "ōkii",
    meaning: "To lớn, bự",
    partOfSpeech: "adjective",
    jlptLevel: "N5",
    exampleJapanese: "東京はとても大きい都市です。",
    exampleRomaji: "Tōkyō wa totemo ōkii toshi desu.",
    exampleMeaning: "Tokyo là một thành phố vô cùng rộng lớn.",
  },
  {
    word: "小さい",
    kana: "ちいさい",
    kanji: "小さい",
    romaji: "chiisai",
    meaning: "Nhỏ, bé",
    partOfSpeech: "adjective",
    jlptLevel: "N5",
    exampleJapanese: "可愛い小さい猫がいます。",
    exampleRomaji: "Kawaii chiisai neko ga imasu.",
    exampleMeaning: "Có một chú mèo con nhỏ nhắn rất dễ thương.",
  },
  {
    word: "これ",
    kana: "これ",
    kanji: null,
    romaji: "kore",
    meaning: "Cái này (gần người nói)",
    partOfSpeech: "pronoun",
    jlptLevel: "N5",
    exampleJapanese: "これを一つください。",
    exampleRomaji: "Kore o hitotsu kudasai.",
    exampleMeaning: "Làm ơn cho tôi lấy cái này.",
  },
  // Chào hỏi & Giao tiếp xã giao
  {
    word: "おはようございます",
    kana: "おはようございます",
    kanji: null,
    romaji: "ohayou gozaimasu",
    meaning: "Chào buổi sáng (lịch sự)",
    partOfSpeech: "greeting",
    jlptLevel: "N5",
    exampleJapanese: "先生、おはようございます！",
    exampleRomaji: "Sensei, ohayou gozaimasu!",
    exampleMeaning: "Em chào thầy/cô buổi sáng ạ!",
  },
  {
    word: "こんばんは",
    kana: "こんばんは",
    kanji: null,
    romaji: "konbanwa",
    meaning: "Chào buổi tối",
    partOfSpeech: "greeting",
    jlptLevel: "N5",
    exampleJapanese: "皆さん、こんばんは。",
    exampleRomaji: "Mina-san, konbanwa.",
    exampleMeaning: "Chào buổi tối mọi người.",
  },
  {
    word: "おやすみなさい",
    kana: "おやすみなさい",
    kanji: null,
    romaji: "oyasuminasai",
    meaning: "Chúc ngủ ngon",
    partOfSpeech: "greeting",
    jlptLevel: "N5",
    exampleJapanese: "もう遅いですね。おやすみなさい。",
    exampleRomaji: "Mou osoi desu ne. Oyasuminasai.",
    exampleMeaning: "Đã muộn rồi nhỉ. Chúc bạn ngủ ngon.",
  },
  {
    word: "さようなら",
    kana: "さようなら",
    kanji: null,
    romaji: "sayounara",
    meaning: "Tạm biệt",
    partOfSpeech: "greeting",
    jlptLevel: "N5",
    exampleJapanese: "また明日。さようなら！",
    exampleRomaji: "Mata ashita. Sayounara!",
    exampleMeaning: "Hẹn gặp lại ngày mai. Tạm biệt nhé!",
  },
  {
    word: "どうもありがとうございます",
    kana: "どうもありがとうございます",
    kanji: null,
    romaji: "doumo arigatou gozaimasu",
    meaning: "Xin chân thành cảm ơn rất nhiều",
    partOfSpeech: "expression",
    jlptLevel: "N5",
    exampleJapanese: "親切にどうもありがとうございます。",
    exampleRomaji: "Shinsetsu ni doumo arigatou gozaimasu.",
    exampleMeaning: "Xin chân thành cảm ơn sự nhiệt tình của bạn.",
  },
  {
    word: "どういたしまして",
    kana: "どういたしまして",
    kanji: null,
    romaji: "douitashimashite",
    meaning: "Không có chi / Không dám đâu",
    partOfSpeech: "expression",
    jlptLevel: "N5",
    exampleJapanese: "いいえ、どういたしまして。",
    exampleRomaji: "Iie, douitashimashite.",
    exampleMeaning: "Dạ không có gì đâu ạ.",
  },
  {
    word: "ごちそうさまでした",
    kana: "ごちそうさまでした",
    kanji: null,
    romaji: "gochisousama deshita",
    meaning: "Cảm ơn vì bữa ăn ngon (nói sau khi ăn)",
    partOfSpeech: "expression",
    jlptLevel: "N5",
    exampleJapanese: "とても美味しかったです。ごちそうさまでした！",
    exampleRomaji: "Totemo oishikatta desu. Gochisousama deshita!",
    exampleMeaning: "Bữa ăn rất là ngon. Cảm ơn vì bữa ăn ạ!",
  },

  // Gia đình & Con người
  {
    word: "家族",
    kana: "かぞく",
    kanji: "家族",
    romaji: "kazoku",
    meaning: "Gia đình",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "私の家族は四人です。",
    exampleRomaji: "Watashi no kazoku wa yo-nin desu.",
    exampleMeaning: "Gia đình tôi có bốn người.",
  },
  {
    word: "父",
    kana: "ちち",
    kanji: "父",
    romaji: "chichi",
    meaning: "Bố / Cha (của mình)",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "父は会社員です。",
    exampleRomaji: "Chichi wa kaishain desu.",
    exampleMeaning: "Bố tôi là nhân viên công ty.",
  },
  {
    word: "母",
    kana: "はは",
    kanji: "母",
    romaji: "haha",
    meaning: "Mẹ (của mình)",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "母は料理が上手です。",
    exampleRomaji: "Haha wa ryouri ga jouzu desu.",
    exampleMeaning: "Mẹ tôi nấu ăn rất giỏi.",
  },
  {
    word: "子供",
    kana: "こども",
    kanji: "子供",
    romaji: "kodomo",
    meaning: "Trẻ em, con cái",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "公園で子供たちが遊んでいます。",
    exampleRomaji: "Kouen de kodomo-tachi ga asonde imasu.",
    exampleMeaning: "Lũ trẻ đang chơi đùa trong công viên.",
  },
  {
    word: "学生",
    kana: "がくせい",
    kanji: "学生",
    romaji: "gakusei",
    meaning: "Học sinh, sinh viên",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "私は大学の学生です。",
    exampleRomaji: "Watashi wa daigaku no gakusei desu.",
    exampleMeaning: "Tôi là sinh viên đại học.",
  },

  // Đồ ăn & Nước uống
  {
    word: "ご飯",
    kana: "ごはん",
    kanji: "ご飯",
    romaji: "gohan",
    meaning: "Cơm / Bữa ăn",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "朝ご飯を食べましたか？",
    exampleRomaji: "Asagohan o tabemashita ka?",
    exampleMeaning: "Bạn đã ăn bữa sáng chưa?",
  },
  {
    word: "パン",
    kana: "パン",
    kanji: null,
    romaji: "pan",
    meaning: "Bánh mì",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "毎朝パンを食べます。",
    exampleRomaji: "Maiasa pan o tabemasu.",
    exampleMeaning: "Mỗi buổi sáng tôi đều ăn bánh mì.",
  },
  {
    word: "水",
    kana: "みず",
    kanji: "水",
    romaji: "mizu",
    meaning: "Nước lọc",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "お水を一杯ください。",
    exampleRomaji: "O-mizu o ippai kudasai.",
    exampleMeaning: "Cho tôi xin một ly nước.",
  },
  {
    word: "お茶",
    kana: "おちゃ",
    kanji: "お茶",
    romaji: "ocha",
    meaning: "Trà xanh Nhật Bản",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "温かいお茶を飲みます。",
    exampleRomaji: "Atatakai ocha o nomimasu.",
    exampleMeaning: "Tôi uống một tách trà nóng ấm.",
  },
  {
    word: "コーヒー",
    kana: "コーヒー",
    kanji: null,
    romaji: "koohii",
    meaning: "Cà phê",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "喫茶店でコーヒーを飲みました。",
    exampleRomaji: "Kissaten de koohii o nomimashita.",
    exampleMeaning: "Tôi đã uống cà phê tại quán nước.",
  },
  {
    word: "魚",
    kana: "さかな",
    kanji: "魚",
    romaji: "sakana",
    meaning: "Cá",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "新鮮な魚を買いました。",
    exampleRomaji: "Shinsen na sakana o kaimashita.",
    exampleMeaning: "Tôi đã mua cá tươi ngon.",
  },
  {
    word: "肉",
    kana: "にく",
    kanji: "肉",
    romaji: "niku",
    meaning: "Thịt (bò, lợn, gà)",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "牛肉が好きです。",
    exampleRomaji: "Gyuuniku ga suki desu.",
    exampleMeaning: "Tôi rất thích ăn thịt bò.",
  },
  {
    word: "野菜",
    kana: "やさい",
    kanji: "野菜",
    romaji: "yasai",
    meaning: "Rau xanh, củ quả",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "野菜をたくさん食べましょう。",
    exampleRomaji: "Yasai o takusan tabemashou.",
    exampleMeaning: "Chúng ta hãy cùng ăn thật nhiều rau nhé.",
  },

  // Địa điểm & Phương tiện đi lại
  {
    word: "家",
    kana: "いえ",
    kanji: "家",
    romaji: "ie",
    meaning: "Nhà ở, gia đình",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "早く家へ帰りたいです。",
    exampleRomaji: "Hayaku ie e kaeritai desu.",
    exampleMeaning: "Tôi muốn về nhà sớm.",
  },
  {
    word: "学校",
    kana: "がっこう",
    kanji: "学校",
    romaji: "gakkou",
    meaning: "Trường học",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "バスで学校へ行きます。",
    exampleRomaji: "Basu de gakkou e ikimasu.",
    exampleMeaning: "Tôi đi đến trường bằng xe buýt.",
  },
  {
    word: "病院",
    kana: "びょういん",
    kanji: "病院",
    romaji: "byouin",
    meaning: "Bệnh viện",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "病院は駅の近くにあります。",
    exampleRomaji: "Byouin wa eki no chikaku ni arimasu.",
    exampleMeaning: "Bệnh viện nằm ở gần nhà ga.",
  },
  {
    word: "電車",
    kana: "でんしゃ",
    kanji: "電車",
    romaji: "densha",
    meaning: "Tàu điện",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "満員電車に乗りました。",
    exampleRomaji: "Man'in densha ni norimashita.",
    exampleMeaning: "Tôi đã lên một chuyến tàu điện chật kín người.",
  },
  {
    word: "新幹線",
    kana: "しんかんせん",
    kanji: "新幹線",
    romaji: "shinkansen",
    meaning: "Tàu cao tốc Shinkansen",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "新幹線はとても速いです。",
    exampleRomaji: "Shinkansen wa totemo hayai desu.",
    exampleMeaning: "Tàu Shinkansen chạy rất nhanh.",
  },
  {
    word: "飛行機",
    kana: "ひこうき",
    kanji: "飛行機",
    romaji: "hikouki",
    meaning: "Máy bay",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "飛行機で日本へ行きます。",
    exampleRomaji: "Hikouki de Nihon e ikimasu.",
    exampleMeaning: "Tôi bay sang Nhật Bản bằng máy bay.",
  },
  {
    word: "車",
    kana: "くるま",
    kanji: "車",
    romaji: "kuruma",
    meaning: "Ô tô, xe hơi",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "新しい車を買いました。",
    exampleRomaji: "Atarashii kuruma o kaimashita.",
    exampleMeaning: "Tôi đã mua một chiếc xe ô tô mới.",
  },

  // Động từ N5 trọng tâm
  {
    word: "話す",
    kana: "はなす",
    kanji: "話す",
    romaji: "hanasu",
    meaning: "Nói chuyện, giao tiếp",
    partOfSpeech: "verb",
    jlptLevel: "N5",
    exampleJapanese: "日本語で話しましょう。",
    exampleRomaji: "Nihongo de hanashimashou.",
    exampleMeaning: "Chúng ta hãy cùng nói chuyện bằng tiếng Nhật nhé.",
  },
  {
    word: "聞く",
    kana: "きく",
    kanji: "聞く",
    romaji: "kiku",
    meaning: "Nghe, hỏi",
    partOfSpeech: "verb",
    jlptLevel: "N5",
    exampleJapanese: "先生の話をよく聞きます。",
    exampleRomaji: "Sensei no hanashi o yoku kikimasu.",
    exampleMeaning: "Tôi chăm chú lắng nghe lời giảng của thầy giáo.",
  },
  {
    word: "読む",
    kana: "よむ",
    kanji: "読む",
    romaji: "yomu",
    meaning: "Đọc (sách, báo)",
    partOfSpeech: "verb",
    jlptLevel: "N5",
    exampleJapanese: "日本の漫画を読みます。",
    exampleRomaji: "Nihon no manga o yomimasu.",
    exampleMeaning: "Tôi đọc truyện tranh manga của Nhật Bản.",
  },
  {
    word: "書く",
    kana: "かく",
    kanji: "書く",
    romaji: "kaku",
    meaning: "Viết, vẽ",
    partOfSpeech: "verb",
    jlptLevel: "N5",
    exampleJapanese: "ノートに漢字を書きます。",
    exampleRomaji: "Nooto ni kanji o kakimasu.",
    exampleMeaning: "Tôi viết chữ Hán Kanji vào vở ghi chép.",
  },
  {
    word: "買う",
    kana: "かう",
    kanji: "買う",
    romaji: "kau",
    meaning: "Mua sắm",
    partOfSpeech: "verb",
    jlptLevel: "N5",
    exampleJapanese: "お土産を買いました。",
    exampleRomaji: "O-miyage o kaimashita.",
    exampleMeaning: "Tôi đã mua quà lưu niệm.",
  },
  {
    word: "待つ",
    kana: "まつ",
    kanji: "待つ",
    romaji: "matsu",
    meaning: "Chờ đợi",
    partOfSpeech: "verb",
    jlptLevel: "N5",
    exampleJapanese: "駅で友達を待ちます。",
    exampleRomaji: "Eki de tomodachi o machimasu.",
    exampleMeaning: "Tôi đứng đợi bạn bè ở nhà ga.",
  },
  {
    word: "帰る",
    kana: "かえる",
    kanji: "帰る",
    romaji: "kaeru",
    meaning: "Trở về (nhà, nước)",
    partOfSpeech: "verb",
    jlptLevel: "N5",
    exampleJapanese: "午後六時にうちへ帰ります。",
    exampleRomaji: "Gogo roku-ji ni uchi e kaerimasu.",
    exampleMeaning: "Lúc sáu giờ chiều tôi trở về nhà.",
  },
  {
    word: "勉強する",
    kana: "べんきょうする",
    kanji: "勉強する",
    romaji: "benkyou suru",
    meaning: "Học tập",
    partOfSpeech: "verb",
    jlptLevel: "N5",
    exampleJapanese: "毎日二時間勉強します。",
    exampleRomaji: "Mainichi ni-jikan benkyou shimasu.",
    exampleMeaning: "Mỗi ngày tôi đều học tập trong hai tiếng.",
  },

  // Tính từ N5 trọng tâm
  {
    word: "高い",
    kana: "たかい",
    kanji: "高い",
    romaji: "takai",
    meaning: "Cao / Đắt tiền",
    partOfSpeech: "adjective",
    jlptLevel: "N5",
    exampleJapanese: "富士山はとても高い山です。",
    exampleRomaji: "Fujisan wa totemo takai yama desu.",
    exampleMeaning: "Núi Phú Sĩ là một ngọn núi rất cao.",
  },
  {
    word: "安い",
    kana: "やすい",
    kanji: "安い",
    romaji: "yasui",
    meaning: "Rẻ tiền / Bình dân",
    partOfSpeech: "adjective",
    jlptLevel: "N5",
    exampleJapanese: "この店は安くて美味しいです。",
    exampleRomaji: "Kono mise wa yasukute oishii desu.",
    exampleMeaning: "Quán này đồ ăn vừa rẻ lại vừa ngon miệng.",
  },
  {
    word: "新しい",
    kana: "あたらしい",
    kanji: "新しい",
    romaji: "atarashii",
    meaning: "Mới mẻ",
    partOfSpeech: "adjective",
    jlptLevel: "N5",
    exampleJapanese: "新しい靴を履きました。",
    exampleRomaji: "Atarashii kutsu o hakimashita.",
    exampleMeaning: "Tôi đã xỏ đôi giày mới.",
  },
  {
    word: "古い",
    kana: "ふるい",
    kanji: "古い",
    romaji: "furui",
    meaning: "Cũ, cổ kính",
    partOfSpeech: "adjective",
    jlptLevel: "N5",
    exampleJapanese: "京都には古いお寺がたくさんあります。",
    exampleRomaji: "Kyouto ni wa furui o-tera ga takusan arimasu.",
    exampleMeaning: "Ở Kyoto có rất nhiều ngôi chùa cổ kính.",
  },
  {
    word: "暑い",
    kana: "あつい",
    kanji: "暑い",
    romaji: "atsui",
    meaning: "Nóng bức (thời tiết)",
    partOfSpeech: "adjective",
    jlptLevel: "N5",
    exampleJapanese: "日本の夏はとても暑いです。",
    exampleRomaji: "Nihon no natsu wa totemo atsui desu.",
    exampleMeaning: "Mùa hè ở Nhật Bản rất là nóng bức.",
  },
  {
    word: "寒い",
    kana: "さむい",
    kanji: "寒い",
    romaji: "samui",
    meaning: "Lạnh buốt (thời tiết)",
    partOfSpeech: "adjective",
    jlptLevel: "N5",
    exampleJapanese: "冬の北海道はとても寒いです。",
    exampleRomaji: "Fuyu no Hokkaidou wa totemo samui desu.",
    exampleMeaning: "Mùa đông ở Hokkaido rất là lạnh giá.",
  },
  {
    word: "綺麗",
    kana: "きれい",
    kanji: "綺麗",
    romaji: "kirei",
    meaning: "Đẹp đẽ, sạch sẽ",
    partOfSpeech: "adjective",
    jlptLevel: "N5",
    exampleJapanese: "桜の花がとても綺麗ですね。",
    exampleRomaji: "Sakura no hana ga totemo kirei desu ne.",
    exampleMeaning: "Hoa anh đào nở đẹp thật đấy nhỉ.",
  },
  {
    word: "元気",
    kana: "げんき",
    kanji: "元気",
    romaji: "genki",
    meaning: "Khỏe mạnh, tràn đầy sinh lực",
    partOfSpeech: "adjective",
    jlptLevel: "N5",
    exampleJapanese: "お元気ですか？ — はい、元気です！",
    exampleRomaji: "O-genki desu ka? — Hai, genki desu!",
    exampleMeaning: "Bạn có khỏe không? — Vâng, tôi rất khỏe!",
  },
  {
    word: "好き",
    kana: "すき",
    kanji: "好き",
    romaji: "suki",
    meaning: "Thích thú, ưa thích",
    partOfSpeech: "adjective",
    jlptLevel: "N5",
    exampleJapanese: "日本のアニメが大好きです。",
    exampleRomaji: "Nihon no anime ga daisuki desu.",
    exampleMeaning: "Tôi cực kỳ yêu thích phim hoạt hình anime Nhật Bản.",
  },
  {
    word: "便利",
    kana: "べんり",
    kanji: "便利",
    romaji: "benri",
    meaning: "Tiện lợi, thuận tiện",
    partOfSpeech: "adjective",
    jlptLevel: "N5",
    exampleJapanese: "コンビニはとても便利です。",
    exampleRomaji: "Konbini wa totemo benri desu.",
    exampleMeaning: "Cửa hàng tiện lợi vô cùng thuận tiện.",
  },

  // Thời gian & Thứ ngày
  {
    word: "今日",
    kana: "きょう",
    kanji: "今日",
    romaji: "kyou",
    meaning: "Hôm nay",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "今日はいい天気ですね。",
    exampleRomaji: "Kyou wa ii tenki desu ne.",
    exampleMeaning: "Hôm nay thời tiết đẹp thật nhỉ.",
  },
  {
    word: "明日",
    kana: "あした",
    kanji: "明日",
    romaji: "ashita",
    meaning: "Ngày mai",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "明日は日曜日です。",
    exampleRomaji: "Ashita wa nichiyoubi desu.",
    exampleMeaning: "Ngày mai là ngày Chủ nhật.",
  },
  {
    word: "昨日",
    kana: "きのう",
    kanji: "昨日",
    romaji: "kinou",
    meaning: "Hôm qua",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "昨日は何をしましたか？",
    exampleRomaji: "Kinou wa nani o shimashita ka?",
    exampleMeaning: "Hôm qua bạn đã làm gì vậy?",
  },
  {
    word: "今",
    kana: "いま",
    kanji: "今",
    romaji: "ima",
    meaning: "Bây giờ, hiện tại",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "今何時ですか？",
    exampleRomaji: "Ima nan-ji desu ka?",
    exampleMeaning: "Bây giờ là mấy giờ rồi ạ?",
  },
  {
    word: "日曜日",
    kana: "にちようび",
    kanji: "日曜日",
    romaji: "nichiyoubi",
    meaning: "Chủ nhật",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "日曜日に友達と遊びます。",
    exampleRomaji: "Nichiyoubi ni tomodachi to asobimasu.",
    exampleMeaning: "Vào ngày Chủ nhật tôi đi chơi cùng bạn bè.",
  },

  // Đồ vật & Mua sắm
  {
    word: "本",
    kana: "ほん",
    kanji: "本",
    romaji: "hon",
    meaning: "Cuốn sách",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "日本語の本を買いました。",
    exampleRomaji: "Nihongo no hon o kaimashita.",
    exampleMeaning: "Tôi đã mua một cuốn sách tiếng Nhật.",
  },
  {
    word: "財布",
    kana: "さいふ",
    kanji: "財布",
    romaji: "saifu",
    meaning: "Cái ví tiền",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "財布を忘れました！",
    exampleRomaji: "Saifu o wasuremashita!",
    exampleMeaning: "Ôi tôi bỏ quên ví tiền mất rồi!",
  },
  {
    word: "時計",
    kana: "とけい",
    kanji: "時計",
    romaji: "tokei",
    meaning: "Đồng hồ",
    partOfSpeech: "noun",
    jlptLevel: "N5",
    exampleJapanese: "この時計はとても正確です。",
    exampleRomaji: "Kono tokei wa totemo seikaku desu.",
    exampleMeaning: "Chiếc đồng hồ này chạy rất chính xác.",
  },
  {
    word: "いくら",
    kana: "いくら",
    kanji: null,
    romaji: "ikura",
    meaning: "Bao nhiêu tiền?",
    partOfSpeech: "pronoun",
    jlptLevel: "N5",
    exampleJapanese: "これはいくらですか？",
    exampleRomaji: "Kore wa ikura desu ka?",
    exampleMeaning: "Cái này giá bao nhiêu tiền vậy ạ?",
  },
];
