export const LESSONS = [
  {
    slug: "hiragana-vowels",
    title: "Hiragana 1: Hàng Nguyên Âm (あ・い・う・え・お)",
    description: "Khởi đầu nền tảng tiếng Nhật với 5 nguyên âm cốt lõi: A, I, U, E, O.",
    level: "N5",
    order: 0,
    xpReward: 50,
    exercises: [
      {
        type: "KANA_RECOGNITION",
        question: "Chữ cái nào sau đây là chữ 'a' (あ)?",
        correctAnswer: "あ",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "あ", isCorrect: true, order: 0 },
          { label: "B", text: "い", isCorrect: false, order: 1 },
          { label: "C", text: "お", isCorrect: false, order: 2 },
          { label: "D", text: "え", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "KANA_TO_ROMAJI",
        question: "Chữ 'い' được đọc là gì trong phiên âm Romaji?",
        correctAnswer: "i",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "e", isCorrect: false, order: 0 },
          { label: "B", text: "i", isCorrect: true, order: 1 },
          { label: "C", text: "u", isCorrect: false, order: 2 },
          { label: "D", text: "o", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "WORD_BUILDING",
        question: "Từ 'あい' (ai) trong tiếng Nhật có nghĩa là gì?",
        correctAnswer: "Tình yêu",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "Tình yêu", isCorrect: true, order: 0 },
          { label: "B", text: "Bầu trời", isCorrect: false, order: 1 },
          { label: "C", text: "Cái nhà", isCorrect: false, order: 2 },
          { label: "D", text: "Dòng sông", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "ROMAJI_TO_KANA",
        question: "Chữ Hiragana tương ứng với âm 'e' là chữ nào?",
        correctAnswer: "え",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "う", isCorrect: false, order: 0 },
          { label: "B", text: "え", isCorrect: true, order: 1 },
          { label: "C", text: "あ", isCorrect: false, order: 2 },
          { label: "D", text: "い", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "hiragana-ka-sa",
    title: "Hiragana 2: Hàng Ka & Hàng Sa (か・さ)",
    description: "Mở rộng bảng chữ với hàng Ka (か・き・く・け・こ) và hàng Sa (さ・し・す・せ・そ).",
    level: "N5",
    order: 1,
    xpReward: 60,
    exercises: [
      {
        type: "KANA_RECOGNITION",
        question: "Ký tự 'か' có cách đọc phiên âm Romaji là gì?",
        correctAnswer: "ka",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "ka", isCorrect: true, order: 0 },
          { label: "B", text: "ki", isCorrect: false, order: 1 },
          { label: "C", text: "ku", isCorrect: false, order: 2 },
          { label: "D", text: "ko", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "SPECIAL_SOUND",
        question: "Trong hàng Sa, chữ nào có phát âm đặc biệt là /ɕi/ ('shi') chứ không phải 'si'?",
        correctAnswer: "し",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "さ", isCorrect: false, order: 0 },
          { label: "B", text: "し", isCorrect: true, order: 1 },
          { label: "C", text: "す", isCorrect: false, order: 2 },
          { label: "D", text: "せ", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Từ ghép 'すし' (sushi) được cấu tạo từ hai ký tự nào?",
        correctAnswer: "す + し",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "す + し", isCorrect: true, order: 0 },
          { label: "B", text: "さ + し", isCorrect: false, order: 1 },
          { label: "C", text: "そ + し", isCorrect: false, order: 2 },
          { label: "D", text: "す + き", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Từ 'かさ' (kasa) trong tiếng Nhật có nghĩa là gì?",
        correctAnswer: "Cây dù / Cái ô",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "Cây dù / Cái ô", isCorrect: true, order: 0 },
          { label: "B", text: "Cái nón", isCorrect: false, order: 1 },
          { label: "C", text: "Đôi giày", isCorrect: false, order: 2 },
          { label: "D", text: "Cái áo", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "hiragana-ta-na",
    title: "Hiragana 3: Hàng Ta, Hàng Na & Hàng Ha",
    description: "Học các ký tự た・ち・つ・て・と, な・に・ぬ・ね・の và は・ひ・ふ・へ・ほ.",
    level: "N5",
    order: 2,
    xpReward: 60,
    exercises: [
      {
        type: "SPECIAL_SOUND",
        question: "Trong hàng Ta, hai chữ cái có phát âm biến âm đặc biệt là gì?",
        correctAnswer: "chi (ち) và tsu (つ)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "chi (ち) và tsu (つ)", isCorrect: true, order: 0 },
          { label: "B", text: "ta (た) và te (て)", isCorrect: false, order: 1 },
          { label: "C", text: "ti và tu", isCorrect: false, order: 2 },
          { label: "D", text: "to và ta", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Từ 'ねこ' (neko) trong tiếng Nhật có nghĩa là gì?",
        correctAnswer: "Con mèo",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "Con mèo", isCorrect: true, order: 0 },
          { label: "B", text: "Con chó", isCorrect: false, order: 1 },
          { label: "C", text: "Con cá", isCorrect: false, order: 2 },
          { label: "D", text: "Con chim", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Từ 'はな' (hana) có nghĩa là gì?",
        correctAnswer: "Bông hoa / Cái mũi",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "Bông hoa / Cái mũi", isCorrect: true, order: 0 },
          { label: "B", text: "Cái miệng", isCorrect: false, order: 1 },
          { label: "C", text: "Ngôi sao", isCorrect: false, order: 2 },
          { label: "D", text: "Cơn mưa", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "KANA_RECOGNITION",
        question: "Chữ Hiragana tương ứng với âm 'fu' là gì?",
        correctAnswer: "ふ",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "は", isCorrect: false, order: 0 },
          { label: "B", text: "ひ", isCorrect: false, order: 1 },
          { label: "C", text: "ふ", isCorrect: true, order: 2 },
          { label: "D", text: "ほ", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "hiragana-ma-wa",
    title: "Hiragana 4: Hàng Ma, Ya, Ra, Wa & Âm N (ん)",
    description: "Hoàn thiện trọn vẹn 46 ký tự Hiragana cơ bản với các hàng cuối cùng.",
    level: "N5",
    order: 3,
    xpReward: 70,
    exercises: [
      {
        type: "VOCABULARY",
        question: "Từ 'さくら' (sakura) gồm các ký tự nào ghép lại?",
        correctAnswer: "さ + く + ら",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "さ + く + ら", isCorrect: true, order: 0 },
          { label: "B", text: "し + く + ら", isCorrect: false, order: 1 },
          { label: "C", text: "す + け + ろ", isCorrect: false, order: 2 },
          { label: "D", text: "さ + こ + り", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Từ 'やま' (yama) có nghĩa là gì?",
        correctAnswer: "Núi, Ngọn núi",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "Núi, Ngọn núi", isCorrect: true, order: 0 },
          { label: "B", text: "Sông ngòi", isCorrect: false, order: 1 },
          { label: "C", text: "Biển cả", isCorrect: false, order: 2 },
          { label: "D", text: "Cánh đồng", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "KANA_RECOGNITION",
        question: "Ký tự duy nhất chỉ có phụ âm và không đi kèm nguyên âm trong tiếng Nhật là gì?",
        correctAnswer: "ん (n)",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "ん (n)", isCorrect: true, order: 0 },
          { label: "B", text: "わ (wa)", isCorrect: false, order: 1 },
          { label: "C", text: "を (wo)", isCorrect: false, order: 2 },
          { label: "D", text: "や (ya)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Từ 'にほん' (nihon) có nghĩa là gì?",
        correctAnswer: "Nhật Bản",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "Nhật Bản", isCorrect: true, order: 0 },
          { label: "B", text: "Việt Nam", isCorrect: false, order: 1 },
          { label: "C", text: "Hàn Quốc", isCorrect: false, order: 2 },
          { label: "D", text: "Trung Quốc", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "basic-greetings",
    title: "Bài Học 5: Những Câu Chào Hỏi Cốt Lõi (Aisatsu)",
    description: "Học cách chào hỏi tự nhiên vào các buổi trong ngày và cảm ơn người Nhật.",
    level: "N5",
    order: 4,
    xpReward: 80,
    exercises: [
      {
        type: "MEANING",
        question: "'こんにちは' (Konnichiwa) được dùng khi nào?",
        correctAnswer: "Chào hỏi vào ban ngày (từ trưa đến chiều)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "Chào hỏi vào ban ngày (từ trưa đến chiều)", isCorrect: true, order: 0 },
          { label: "B", text: "Chào trước khi đi ngủ", isCorrect: false, order: 1 },
          { label: "C", text: "Chào vào sáng sớm vừa thức dậy", isCorrect: false, order: 2 },
          { label: "D", text: "Chào khi tạm biệt mãi mãi", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "MEANING",
        question: "Câu chào buổi sáng lịch sự trong tiếng Nhật là gì?",
        correctAnswer: "おはようございます (Ohayō gozaimasu)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "おはようございます (Ohayō gozaimasu)", isCorrect: true, order: 0 },
          { label: "B", text: "こんばんは (Konbanwa)", isCorrect: false, order: 1 },
          { label: "C", text: "さようなら (Sayōnara)", isCorrect: false, order: 2 },
          { label: "D", text: "おやすみなさい (Oyasuminasai)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "MEANING",
        question: "Để nói lời cảm ơn chân thành, bạn dùng câu nào?",
        correctAnswer: "ありがとうございます (Arigatō gozaimasu)",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "ありがとうございます (Arigatō gozaimasu)", isCorrect: true, order: 0 },
          { label: "B", text: "すみません (Sumimasen)", isCorrect: false, order: 1 },
          { label: "C", text: "ごめんなさい (Gomennasai)", isCorrect: false, order: 2 },
          { label: "D", text: "いいえ (Iie)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "MEANING",
        question: "Trước khi đi ngủ, câu chúc ngủ ngon lịch sự là gì?",
        correctAnswer: "おやすみなさい (Oyasuminasai)",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "おやすみなさい (Oyasuminasai)", isCorrect: true, order: 0 },
          { label: "B", text: "こんばんは (Konbanwa)", isCorrect: false, order: 1 },
          { label: "C", text: "いただきます (Itadakimasu)", isCorrect: false, order: 2 },
          { label: "D", text: "じゃあね (Jaa ne)", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "self-introduction",
    title: "Bài Học 6: Tự Giới Thiệu Bản Thân (Jikoshoukai)",
    description: "Tự tin giới thiệu tên tuổi, quốc tịch và nói câu 'Rất mong nhận được sự giúp đỡ'.",
    level: "N5",
    order: 5,
    xpReward: 80,
    exercises: [
      {
        type: "MEANING",
        question: "Từ đầu tiên luôn nói khi bắt đầu giới thiệu bản thân là gì?",
        correctAnswer: "はじめまして (Hajimemashite - Rất vui được gặp bạn lần đầu)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "はじめまして (Hajimemashite - Rất vui được gặp bạn lần đầu)", isCorrect: true, order: 0 },
          { label: "B", text: "さようなら (Sayōnara)", isCorrect: false, order: 1 },
          { label: "C", text: "またね (Mata ne)", isCorrect: false, order: 2 },
          { label: "D", text: "お邪魔します (Ojamashimasu)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "GRAMMAR",
        question: "Để nói 'Tôi là Nam' trong tiếng Nhật, câu chuẩn là gì?",
        correctAnswer: "わたしはナムです。(Watashi wa Namu desu.)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "わたしはナムです。(Watashi wa Namu desu.)", isCorrect: true, order: 0 },
          { label: "B", text: "わたしがナムです。(Watashi ga Namu desu.)", isCorrect: false, order: 1 },
          { label: "C", text: "ナムはわたしです。(Namu wa watashi desu.)", isCorrect: false, order: 2 },
          { label: "D", text: "わたしナム。(Watashi Namu.)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "MEANING",
        question: "Câu kết thúc màn chào hỏi: 'よろしくお願いします' (Yoroshiku onegaishimasu) nghĩa là gì?",
        correctAnswer: "Rất mong nhận được sự giúp đỡ của quý bạn",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "Rất mong nhận được sự giúp đỡ của quý bạn", isCorrect: true, order: 0 },
          { label: "B", text: "Hẹn gặp lại vào ngày mai", isCorrect: false, order: 1 },
          { label: "C", text: "Tôi không phiền đâu", isCorrect: false, order: 2 },
          { label: "D", text: "Tạm biệt và chúc may mắn", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "numbers-counters",
    title: "Bài Học 7: Số Đếm từ 1 đến 10 (Suuji)",
    description: "Làm chủ cách đếm từ 1 đến 10 và các đơn vị đếm cơ bản trong đời sống.",
    level: "N5",
    order: 6,
    xpReward: 80,
    exercises: [
      {
        type: "NUMBERS",
        question: "Số 3 trong tiếng Nhật đọc là gì?",
        correctAnswer: "さん (san)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "いち (ichi)", isCorrect: false, order: 0 },
          { label: "B", text: "に (ni)", isCorrect: false, order: 1 },
          { label: "C", text: "さん (san)", isCorrect: true, order: 2 },
          { label: "D", text: "よん (yon)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "NUMBERS",
        question: "Số 7 trong tiếng Nhật có hai cách đọc phổ biến là gì?",
        correctAnswer: "なな (nana) hoặc しち (shichi)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "なな (nana) hoặc しち (shichi)", isCorrect: true, order: 0 },
          { label: "B", text: "ろく (roku) hoặc はち (hachi)", isCorrect: false, order: 1 },
          { label: "C", text: "きゅう (kyuu) hoặc じゅう (juu)", isCorrect: false, order: 2 },
          { label: "D", text: "よん (yon) hoặc ご (go)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "NUMBERS",
        question: "Số 10 trong tiếng Nhật đọc là gì?",
        correctAnswer: "じゅう (juu)",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "じゅう (juu)", isCorrect: true, order: 0 },
          { label: "B", text: "きゅう (kyuu)", isCorrect: false, order: 1 },
          { label: "C", text: "はち (hachi)", isCorrect: false, order: 2 },
          { label: "D", text: "ひゃく (hyaku)", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "shopping-prices",
    title: "Bài Học 8: Mua Sắm & Hỏi Giá Tiền (Kaimono)",
    description: "Hỏi giá 'Cái này bao nhiêu tiền?' và cách dùng đơn vị tiền tệ Yên (円).",
    level: "N5",
    order: 7,
    xpReward: 90,
    exercises: [
      {
        type: "PHRASE",
        question: "Để hỏi 'Cái này bao nhiêu tiền?', bạn nói câu nào?",
        correctAnswer: "これはいくらですか？ (Kore wa ikura desu ka?)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "これはいくらですか？ (Kore wa ikura desu ka?)", isCorrect: true, order: 0 },
          { label: "B", text: "これは何ですか？ (Kore wa nan desu ka?)", isCorrect: false, order: 1 },
          { label: "C", text: "どこですか？ (Doko desu ka?)", isCorrect: false, order: 2 },
          { label: "D", text: "だれですか？ (Dare desu ka?)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "PHRASE",
        question: "Khi chọn xong món đồ và nói với thu ngân: 'Lấy cho tôi cái này', bạn nói gì?",
        correctAnswer: "これをください。(Kore o kudasai.)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "これをください。(Kore o kudasai.)", isCorrect: true, order: 0 },
          { label: "B", text: "これを見ます。(Kore o mimasu.)", isCorrect: false, order: 1 },
          { label: "C", text: "これを行きます。(Kore o ikimasu.)", isCorrect: false, order: 2 },
          { label: "D", text: "これを食べます。(Kore o tabemasu.)", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "food-ordering",
    title: "Bài Học 9: Ẩm Thực & Gọi Món Tại Quán Ăn",
    description: "Nói câu chúc ngon miệng, cảm ơn đầu bếp và gọi các món ăn cơ bản.",
    level: "N5",
    order: 8,
    xpReward: 90,
    exercises: [
      {
        type: "CULTURE",
        question: "Trước khi bắt đầu ăn cơm, người Nhật luôn chắp tay và nói câu gì?",
        correctAnswer: "いただきます (Itadakimasu)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "いただきます (Itadakimasu)", isCorrect: true, order: 0 },
          { label: "B", text: "ごちそうさまでした (Gochisōsama deshita)", isCorrect: false, order: 1 },
          { label: "C", text: "乾杯 (Kanpai)", isCorrect: false, order: 2 },
          { label: "D", text: "どうも (Dōmo)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "CULTURE",
        question: "Sau khi ăn xong để cảm ơn người nấu và bữa ăn ngon, bạn nói gì?",
        correctAnswer: "ごちそうさまでした (Gochisōsama deshita)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "ごちそうさまでした (Gochisōsama deshita)", isCorrect: true, order: 0 },
          { label: "B", text: "いただきます (Itadakimasu)", isCorrect: false, order: 1 },
          { label: "C", text: "お腹がいっぱいです (Onaka ga ippai desu)", isCorrect: false, order: 2 },
          { label: "D", text: "また来ます (Mata kimasu)", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "directions-locations",
    title: "Bài Học 10: Chỉ Đường & Hỏi Vị Trí (Koko / Soko / Asoko)",
    description: "Hỏi đường đi đến nhà ga, nhà vệ sinh và phân biệt các đại từ chỉ nơi chốn.",
    level: "N5",
    order: 9,
    xpReward: 100,
    exercises: [
      {
        type: "PHRASE",
        question: "Muốn hỏi lịch sự: 'Xin lỗi, nhà vệ sinh ở đâu ạ?', bạn nói câu nào?",
        correctAnswer: "すみません、トイレはどこですか？ (Sumimasen, toire wa doko desu ka?)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "すみません、トイレはどこですか？ (Sumimasen, toire wa doko desu ka?)", isCorrect: true, order: 0 },
          { label: "B", text: "トイレはありますか？ (Toire wa arimasu ka?)", isCorrect: false, order: 1 },
          { label: "C", text: "トイレへ行きます。(Toire e ikimasu.)", isCorrect: false, order: 2 },
          { label: "D", text: "トイレはいくらですか？ (Toire wa ikura desu ka?)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Chữ '駅' (eki) trong tiếng Nhật có nghĩa là gì?",
        correctAnswer: "Nhà ga (xe lửa, tàu điện)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "Nhà ga (xe lửa, tàu điện)", isCorrect: true, order: 0 },
          { label: "B", text: "Sân bay", isCorrect: false, order: 1 },
          { label: "C", text: "Bến xe buýt", isCorrect: false, order: 2 },
          { label: "D", text: "Cảng biển", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "'ここ' (koko), 'そこ' (soko), 'あそこ' (asoko) khác nhau như thế nào?",
        correctAnswer: "ここ = chỗ tôi đứng, そこ = chỗ bạn đứng, あそこ = chỗ xa cả hai",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "ここ = chỗ tôi đứng, そこ = chỗ bạn đứng, あそこ = chỗ xa cả hai", isCorrect: true, order: 0 },
          { label: "B", text: "ここ = bên trái, そこ = bên phải, あそこ = đằng trước", isCorrect: false, order: 1 },
          { label: "C", text: "ここ = gần, そこ = trung bình, あそこ = gần nhất", isCorrect: false, order: 2 },
          { label: "D", text: "Cả ba đều chỉ cùng một vị trí", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "dakuten-sounds",
    title: "Bài Học 11: Biến Âm Dakuten & Handakuten (が・ざ・だ・ば・ぱ)",
    description: "Nắm vững cách thêm dấu ゛(dakuten) và ゜(handakuten) để tạo ra các âm mới trong tiếng Nhật.",
    level: "N5",
    order: 10,
    xpReward: 90,
    exercises: [
      {
        type: "SPECIAL_SOUND",
        question: "Chữ 'か' (ka) khi thêm dấu dakuten (゛) sẽ trở thành âm nào?",
        correctAnswer: "が (ga)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "が (ga)", isCorrect: true, order: 0 },
          { label: "B", text: "ぱ (pa)", isCorrect: false, order: 1 },
          { label: "C", text: "ざ (za)", isCorrect: false, order: 2 },
          { label: "D", text: "だ (da)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "KANA_RECOGNITION",
        question: "Dấu handakuten (゜) chỉ được thêm vào hàng nào để tạo âm 'P'?",
        correctAnswer: "Hàng Ha (は・ひ・ふ・へ・ほ) → (ぱ・ぴ・ぷ・ぺ・ぽ)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "Hàng Ha (は・ひ・ふ・へ・ほ) → (ぱ・ぴ・ぷ・ぺ・ぽ)", isCorrect: true, order: 0 },
          { label: "B", text: "Hàng Ka (か・き・く・け・こ)", isCorrect: false, order: 1 },
          { label: "C", text: "Hàng Sa (さ・し・す・せ・そ)", isCorrect: false, order: 2 },
          { label: "D", text: "Hàng Na (な・に・ぬ・ね・の)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Từ 'ばら' (bara) trong tiếng Nhật có nghĩa là gì?",
        correctAnswer: "Bông hồng",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "Bông hồng", isCorrect: true, order: 0 },
          { label: "B", text: "Bông anh đào", isCorrect: false, order: 1 },
          { label: "C", text: "Bông cúc", isCorrect: false, order: 2 },
          { label: "D", text: "Bông sen", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "KANA_TO_ROMAJI",
        question: "Âm 'ぞ' (zo) được tạo ra từ chữ nào + dấu dakuten?",
        correctAnswer: "そ (so) + dakuten",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "そ (so) + dakuten", isCorrect: true, order: 0 },
          { label: "B", text: "ず (zu) + dakuten", isCorrect: false, order: 1 },
          { label: "C", text: "ざ (za) + dakuten", isCorrect: false, order: 2 },
          { label: "D", text: "ぜ (ze) + dakuten", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "katakana-basics",
    title: "Bài Học 12: Katakana Cơ Bản (ア・イ・ウ・エ・オ đến ハ hàng)",
    description: "Học bảng chữ Katakana dùng để viết từ ngoại lai và tên nước ngoài.",
    level: "N5",
    order: 11,
    xpReward: 100,
    exercises: [
      {
        type: "KANA_RECOGNITION",
        question: "Katakana 'ア' (a) tương ứng với Hiragana nào?",
        correctAnswer: "あ (a)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "あ (a)", isCorrect: true, order: 0 },
          { label: "B", text: "い (i)", isCorrect: false, order: 1 },
          { label: "C", text: "う (u)", isCorrect: false, order: 2 },
          { label: "D", text: "え (e)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Từ ngoại lai 'コーヒー' (kōhī) có nghĩa là gì?",
        correctAnswer: "Cà phê (Coffee)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "Cà phê (Coffee)", isCorrect: true, order: 0 },
          { label: "B", text: "Trà (Tea)", isCorrect: false, order: 1 },
          { label: "C", text: "Nước ép (Juice)", isCorrect: false, order: 2 },
          { label: "D", text: "Sữa (Milk)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Từ 'アイスクリーム' (aisu kurīmu) được mượn từ tiếng Anh và nghĩa là gì?",
        correctAnswer: "Kem (Ice cream)",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "Kem (Ice cream)", isCorrect: true, order: 0 },
          { label: "B", text: "Bánh ngọt", isCorrect: false, order: 1 },
          { label: "C", text: "Sô-cô-la", isCorrect: false, order: 2 },
          { label: "D", text: "Kẹo mút", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "KANA_TO_ROMAJI",
        question: "Katakana 'ニ' đọc là gì?",
        correctAnswer: "ni",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "ni", isCorrect: true, order: 0 },
          { label: "B", text: "nu", isCorrect: false, order: 1 },
          { label: "C", text: "ne", isCorrect: false, order: 2 },
          { label: "D", text: "na", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "i-adjectives",
    title: "Bài Học 13: Tính Từ い (I-Adjectives) — Nóng, Lạnh, Đẹp",
    description: "Học cách dùng tính từ đuôi -い mô tả sự vật, thời tiết và cảm xúc trong câu.",
    level: "N5",
    order: 12,
    xpReward: 100,
    exercises: [
      {
        type: "GRAMMAR",
        question: "'おいしい' (oishii) nghĩa là gì và thuộc nhóm tính từ nào?",
        correctAnswer: "Ngon / Tính từ đuôi -い (i-adjective)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "Ngon / Tính từ đuôi -い (i-adjective)", isCorrect: true, order: 0 },
          { label: "B", text: "Đẹp / Tính từ đuôi -な (na-adjective)", isCorrect: false, order: 1 },
          { label: "C", text: "Nóng / Danh từ", isCorrect: false, order: 2 },
          { label: "D", text: "Lạnh / Động từ", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "GRAMMAR",
        question: "Để phủ định 'おいしい' thành 'không ngon', ta đổi đuôi thành gì?",
        correctAnswer: "おいしくない (oishiku nai)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "おいしくない (oishiku nai)", isCorrect: true, order: 0 },
          { label: "B", text: "おいしいじゃない (oishii ja nai)", isCorrect: false, order: 1 },
          { label: "C", text: "おいしくです (oishiku desu)", isCorrect: false, order: 2 },
          { label: "D", text: "おいしいではない (oishii de wa nai)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Cặp tính từ trái nghĩa 'あつい (atsui) / さむい (samui)' nghĩa là gì?",
        correctAnswer: "Nóng / Lạnh (nhiệt độ)",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "Nóng / Lạnh (nhiệt độ)", isCorrect: true, order: 0 },
          { label: "B", text: "To / Nhỏ", isCorrect: false, order: 1 },
          { label: "C", text: "Cao / Thấp", isCorrect: false, order: 2 },
          { label: "D", text: "Nhanh / Chậm", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "GRAMMAR",
        question: "Câu 'Cái ô tô này đắt tiền' nói bằng tiếng Nhật là gì?",
        correctAnswer: "この車は高いです。(Kono kuruma wa takai desu.)",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "この車は高いです。(Kono kuruma wa takai desu.)", isCorrect: true, order: 0 },
          { label: "B", text: "この車は高くです。(Kono kuruma wa takaku desu.)", isCorrect: false, order: 1 },
          { label: "C", text: "この車が高さです。(Kono kuruma ga takasa desu.)", isCorrect: false, order: 2 },
          { label: "D", text: "この車は高いじゃ。(Kono kuruma wa takai ja.)", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "basic-verbs",
    title: "Bài Học 14: Động Từ Cơ Bản — Đi, Ăn, Uống, Mua, Đọc",
    description: "Học cách chia động từ thể -ます (masu) lịch sự và dùng trong câu đơn giản.",
    level: "N5",
    order: 13,
    xpReward: 110,
    exercises: [
      {
        type: "GRAMMAR",
        question: "Động từ 'đi' lịch sự trong tiếng Nhật là gì?",
        correctAnswer: "いきます (ikimasu)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "いきます (ikimasu)", isCorrect: true, order: 0 },
          { label: "B", text: "たべます (tabemasu)", isCorrect: false, order: 1 },
          { label: "C", text: "のみます (nomimasu)", isCorrect: false, order: 2 },
          { label: "D", text: "かいます (kaimasu)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "GRAMMAR",
        question: "Câu 'Tôi ăn sushi' nói bằng tiếng Nhật là gì?",
        correctAnswer: "わたしはすしをたべます。(Watashi wa sushi o tabemasu.)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "わたしはすしをたべます。(Watashi wa sushi o tabemasu.)", isCorrect: true, order: 0 },
          { label: "B", text: "わたしはすしがたべます。(Watashi wa sushi ga tabemasu.)", isCorrect: false, order: 1 },
          { label: "C", text: "わたしにすしをたべます。(Watashi ni sushi o tabemasu.)", isCorrect: false, order: 2 },
          { label: "D", text: "わたしとすしをたべます。(Watashi to sushi o tabemasu.)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "GRAMMAR",
        question: "Để nói 'Tôi không uống cà phê', câu phủ định đúng là gì?",
        correctAnswer: "コーヒーをのみません。(Kōhī o nomimasen.)",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "コーヒーをのみません。(Kōhī o nomimasen.)", isCorrect: true, order: 0 },
          { label: "B", text: "コーヒーをのみないです。(Kōhī o nomi nai desu.)", isCorrect: false, order: 1 },
          { label: "C", text: "コーヒーをのみくない。(Kōhī o nomiku nai.)", isCorrect: false, order: 2 },
          { label: "D", text: "コーヒーがのみません。(Kōhī ga nomimasen.)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "GRAMMAR",
        question: "'よみます' (yomimasu) nghĩa là gì?",
        correctAnswer: "Đọc (sách, báo, truyện)",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "Đọc (sách, báo, truyện)", isCorrect: true, order: 0 },
          { label: "B", text: "Viết (chữ, thư)", isCorrect: false, order: 1 },
          { label: "C", text: "Xem (phim, TV)", isCorrect: false, order: 2 },
          { label: "D", text: "Nghe (nhạc, tin tức)", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "time-calendar",
    title: "Bài Học 15: Thời Gian & Lịch Nhật Bản (Jikan & Tsuki)",
    description: "Đọc giờ, nói ngày trong tuần, tháng và hỏi 'Bây giờ mấy giờ?' một cách tự nhiên.",
    level: "N5",
    order: 14,
    xpReward: 110,
    exercises: [
      {
        type: "VOCABULARY",
        question: "Để hỏi 'Bây giờ là mấy giờ?', bạn nói gì?",
        correctAnswer: "いま、なんじですか？ (Ima, nanji desu ka?)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "いま、なんじですか？ (Ima, nanji desu ka?)", isCorrect: true, order: 0 },
          { label: "B", text: "きょうはなんようびですか？ (Kyō wa nan-yōbi desu ka?)", isCorrect: false, order: 1 },
          { label: "C", text: "なんがつですか？ (Nan-gatsu desu ka?)", isCorrect: false, order: 2 },
          { label: "D", text: "いつですか？ (Itsu desu ka?)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Các ngày trong tuần tiếng Nhật có cấu trúc: _曜日 (yōbi). Thứ 2 (Thứ Hai) là gì?",
        correctAnswer: "月曜日 (Getsuyōbi) — 月 là Mặt Trăng/Tháng",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "月曜日 (Getsuyōbi) — 月 là Mặt Trăng/Tháng", isCorrect: true, order: 0 },
          { label: "B", text: "火曜日 (Kayōbi) — 火 là Lửa", isCorrect: false, order: 1 },
          { label: "C", text: "水曜日 (Suiyōbi) — 水 là Nước", isCorrect: false, order: 2 },
          { label: "D", text: "木曜日 (Mokuyōbi) — 木 là Gỗ/Cây", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Tháng 3 (tháng Ba) trong tiếng Nhật là gì?",
        correctAnswer: "さんがつ (san-gatsu)",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "さんがつ (san-gatsu)", isCorrect: true, order: 0 },
          { label: "B", text: "みっかがつ (mikkagatu)", isCorrect: false, order: 1 },
          { label: "C", text: "ちがつ (chigatsu)", isCorrect: false, order: 2 },
          { label: "D", text: "しがつ (shi-gatsu)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "CULTURE",
        question: "Người Nhật thường dùng hai hệ thống lịch: Lịch Dương và Nengo (Niên hiệu). Niên hiệu hiện tại của Nhật là gì?",
        correctAnswer: "Reiwa (令和) — Bắt đầu từ năm 2019 khi Nhật Hoàng Naruhito lên ngôi",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "Reiwa (令和) — Bắt đầu từ năm 2019 khi Nhật Hoàng Naruhito lên ngôi", isCorrect: true, order: 0 },
          { label: "B", text: "Heisei (平成) — Niên hiệu của Nhật Hoàng Akihito", isCorrect: false, order: 1 },
          { label: "C", text: "Showa (昭和) — Thời kỳ Nhật Hoàng Hirohito", isCorrect: false, order: 2 },
          { label: "D", text: "Meiji (明治) — Thời kỳ duy tân Nhật Bản", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "japanese-particles",
    title: "Bài Học 16: Trợ Từ Tiếng Nhật — は・が・を・に・で",
    description: "Nắm vững 5 trợ từ cốt lõi nhất quyết định ý nghĩa mọi câu trong tiếng Nhật.",
    level: "N5",
    order: 15,
    xpReward: 120,
    exercises: [
      {
        type: "GRAMMAR",
        question: "Trợ từ 'は' (wa) trong câu đóng vai trò gì?",
        correctAnswer: "Đánh dấu chủ đề của câu (Topic marker)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "Đánh dấu chủ đề của câu (Topic marker)", isCorrect: true, order: 0 },
          { label: "B", text: "Đánh dấu tân ngữ trực tiếp (Object marker)", isCorrect: false, order: 1 },
          { label: "C", text: "Đánh dấu địa điểm (Location marker)", isCorrect: false, order: 2 },
          { label: "D", text: "Đánh dấu phương tiện (Instrument marker)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "GRAMMAR",
        question: "Trợ từ 'を' (o/wo) được dùng để làm gì trong câu?",
        correctAnswer: "Đánh dấu tân ngữ trực tiếp mà động từ tác động lên (Object marker)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "Đánh dấu tân ngữ trực tiếp mà động từ tác động lên (Object marker)", isCorrect: true, order: 0 },
          { label: "B", text: "Đánh dấu chủ đề (Topic marker)", isCorrect: false, order: 1 },
          { label: "C", text: "Đánh dấu chủ ngữ nhấn mạnh (Subject marker)", isCorrect: false, order: 2 },
          { label: "D", text: "Nối hai danh từ lại (Connector)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "GRAMMAR",
        question: "Trong câu 'としょかんで本を読みます', trợ từ 'で' có chức năng gì?",
        correctAnswer: "Chỉ địa điểm xảy ra hành động (Location of action)",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "Chỉ địa điểm xảy ra hành động (Location of action)", isCorrect: true, order: 0 },
          { label: "B", text: "Chỉ phương tiện di chuyển", isCorrect: false, order: 1 },
          { label: "C", text: "Chỉ thời gian", isCorrect: false, order: 2 },
          { label: "D", text: "Chỉ mục đích", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "GRAMMAR",
        question: "Điền trợ từ đúng vào chỗ trống: 'えき ___ いきます' (Đi đến nhà ga)",
        correctAnswer: "に (ni) — trợ từ chỉ điểm đến/hướng đến",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "に (ni) — trợ từ chỉ điểm đến/hướng đến", isCorrect: true, order: 0 },
          { label: "B", text: "で (de) — trợ từ chỉ địa điểm hành động", isCorrect: false, order: 1 },
          { label: "C", text: "を (o) — trợ từ chỉ tân ngữ", isCorrect: false, order: 2 },
          { label: "D", text: "は (wa) — trợ từ chỉ chủ đề", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "family-members",
    title: "Bài Học 17: Các Thành Viên Trong Gia Đình (Kazoku)",
    description: "Học từ vựng về gia đình và phân biệt cách gọi khi nói về gia đình mình vs gia đình người khác.",
    level: "N5",
    order: 16,
    xpReward: 110,
    exercises: [
      {
        type: "VOCABULARY",
        question: "'おかあさん' (okāsan) và 'はは' (haha) đều chỉ 'mẹ'. Khác biệt là gì?",
        correctAnswer: "おかあさん dùng khi nói về mẹ của người khác; はは dùng khi nói về mẹ của mình",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "おかあさん dùng khi nói về mẹ của người khác; はは dùng khi nói về mẹ của mình", isCorrect: true, order: 0 },
          { label: "B", text: "おかあさん là cách nói trang trọng; はは là cách nói thân mật trong gia đình", isCorrect: false, order: 1 },
          { label: "C", text: "Cả hai giống nhau hoàn toàn", isCorrect: false, order: 2 },
          { label: "D", text: "おかあさん là miền Nam; はは là miền Bắc Nhật Bản", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Từ nào trong tiếng Nhật chỉ 'anh/em trai' (younger brother)?",
        correctAnswer: "おとうと (otōto)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "おとうと (otōto)", isCorrect: true, order: 0 },
          { label: "B", text: "あに (ani)", isCorrect: false, order: 1 },
          { label: "C", text: "いもうと (imōto)", isCorrect: false, order: 2 },
          { label: "D", text: "おねえさん (onēsan)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "'そふ' (sofu) và 'そぼ' (sobo) nghĩa là gì?",
        correctAnswer: "そふ = Ông nội/ngoại; そぼ = Bà nội/ngoại",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "そふ = Ông nội/ngoại; そぼ = Bà nội/ngoại", isCorrect: true, order: 0 },
          { label: "B", text: "そふ = Bố; そぼ = Mẹ", isCorrect: false, order: 1 },
          { label: "C", text: "そふ = Anh trai; そぼ = Chị gái", isCorrect: false, order: 2 },
          { label: "D", text: "そふ = Chú bác; そぼ = Cô dì", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "GRAMMAR",
        question: "Giới thiệu gia đình: 'Đây là bố tôi', cách nói đúng là?",
        correctAnswer: "こちらはわたしのちちです。(Kochira wa watashi no chichi desu.)",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "こちらはわたしのちちです。(Kochira wa watashi no chichi desu.)", isCorrect: true, order: 0 },
          { label: "B", text: "これはおとうさんです。(Kore wa otōsan desu.)", isCorrect: false, order: 1 },
          { label: "C", text: "ここはわたしのちちです。(Koko wa watashi no chichi desu.)", isCorrect: false, order: 2 },
          { label: "D", text: "こちらはわたしがちちです。(Kochira wa watashi ga chichi desu.)", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "weather-seasons",
    title: "Bài Học 18: Thời Tiết & Bốn Mùa Nhật Bản (Kisetsu)",
    description: "Nói về thời tiết hàng ngày và hiểu văn hóa 4 mùa đặc trưng của Nhật Bản.",
    level: "N5",
    order: 17,
    xpReward: 110,
    exercises: [
      {
        type: "VOCABULARY",
        question: "Từ 'はれ' (hare) trong dự báo thời tiết có nghĩa là gì?",
        correctAnswer: "Trời nắng / Quang đãng",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "Trời nắng / Quang đãng", isCorrect: true, order: 0 },
          { label: "B", text: "Trời mưa", isCorrect: false, order: 1 },
          { label: "C", text: "Trời nhiều mây", isCorrect: false, order: 2 },
          { label: "D", text: "Có tuyết", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Bốn mùa trong tiếng Nhật là: はる・なつ・あき・ふゆ. Mùa nào ứng với mùa đông?",
        correctAnswer: "ふゆ (fuyu)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "ふゆ (fuyu)", isCorrect: true, order: 0 },
          { label: "B", text: "なつ (natsu)", isCorrect: false, order: 1 },
          { label: "C", text: "あき (aki)", isCorrect: false, order: 2 },
          { label: "D", text: "はる (haru)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "CULTURE",
        question: "'花見' (Hanami) là hoạt động văn hóa đặc trưng của mùa nào?",
        correctAnswer: "Mùa xuân — Ngắm hoa anh đào (桜 Sakura) nở rộ",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "Mùa xuân — Ngắm hoa anh đào (桜 Sakura) nở rộ", isCorrect: true, order: 0 },
          { label: "B", text: "Mùa hè — Ngắm hoa hướng dương trên đồng", isCorrect: false, order: 1 },
          { label: "C", text: "Mùa thu — Ngắm lá phong đỏ (紅葉 Momiji)", isCorrect: false, order: 2 },
          { label: "D", text: "Mùa đông — Ngắm tuyết rơi ở Hokkaido", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "GRAMMAR",
        question: "Câu 'Hôm nay trời nóng nhỉ?' nói bằng tiếng Nhật là gì?",
        correctAnswer: "きょうはあついですね。(Kyō wa atsui desu ne.)",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "きょうはあついですね。(Kyō wa atsui desu ne.)", isCorrect: true, order: 0 },
          { label: "B", text: "きょうはあついですか？ (Kyō wa atsui desu ka?)", isCorrect: false, order: 1 },
          { label: "C", text: "きょうがあついですよ。(Kyō ga atsui desu yo.)", isCorrect: false, order: 2 },
          { label: "D", text: "きょうあついですわ。(Kyō atsui desu wa.)", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "hobbies-activities",
    title: "Bài Học 19: Sở Thích & Hoạt Động Giải Trí (Shumi)",
    description: "Nói về sở thích, hỏi người khác sở thích gì và diễn đạt mức độ yêu thích.",
    level: "N5",
    order: 18,
    xpReward: 120,
    exercises: [
      {
        type: "PHRASE",
        question: "Để hỏi 'Bạn có sở thích gì?', câu hỏi tự nhiên trong tiếng Nhật là?",
        correctAnswer: "しゅみはなんですか？ (Shumi wa nan desu ka?)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "しゅみはなんですか？ (Shumi wa nan desu ka?)", isCorrect: true, order: 0 },
          { label: "B", text: "なにがすきですか？ (Nani ga suki desu ka?)", isCorrect: false, order: 1 },
          { label: "C", text: "なにをしますか？ (Nani o shimasu ka?)", isCorrect: false, order: 2 },
          { label: "D", text: "どんなことがすきですか？ (Donna koto ga suki desu ka?)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "GRAMMAR",
        question: "Để nói 'Tôi thích âm nhạc', câu đúng là gì?",
        correctAnswer: "おんがくがすきです。(Ongaku ga suki desu.)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "おんがくがすきです。(Ongaku ga suki desu.)", isCorrect: true, order: 0 },
          { label: "B", text: "おんがくをすきです。(Ongaku o suki desu.)", isCorrect: false, order: 1 },
          { label: "C", text: "おんがくはすきです。(Ongaku wa suki desu.)", isCorrect: false, order: 2 },
          { label: "D", text: "おんがくにすきです。(Ongaku ni suki desu.)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "'えいがをみること' (eiga o miru koto) là sở thích gì?",
        correctAnswer: "Xem phim (điện ảnh)",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "Xem phim (điện ảnh)", isCorrect: true, order: 0 },
          { label: "B", text: "Đọc manga", isCorrect: false, order: 1 },
          { label: "C", text: "Chơi game", isCorrect: false, order: 2 },
          { label: "D", text: "Nghe nhạc", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "GRAMMAR",
        question: "Mức độ yêu thích 'だいすき' (daisuki) mạnh hơn 'すき' (suki) như thế nào?",
        correctAnswer: "だいすき = Rất thích / Yêu thích; すき = Thích",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "だいすき = Rất thích / Yêu thích; すき = Thích", isCorrect: true, order: 0 },
          { label: "B", text: "Giống nhau hoàn toàn, chỉ khác vùng miền", isCorrect: false, order: 1 },
          { label: "C", text: "だいすき = Thích; すき = Rất thích", isCorrect: false, order: 2 },
          { label: "D", text: "だいすき dùng cho đồ vật; すき dùng cho người", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "at-hospital-pharmacy",
    title: "Bài Học 20: Tình Huống Khẩn Cấp — Bệnh Viện & Nhà Thuốc",
    description: "Học cách diễn đạt triệu chứng bệnh, xin thuốc và gọi cấp cứu ở Nhật Bản.",
    level: "N5",
    order: 19,
    xpReward: 130,
    exercises: [
      {
        type: "PHRASE",
        question: "Để nói 'Tôi bị đau đầu' với bác sĩ, bạn nói câu nào?",
        correctAnswer: "あたまがいたいです。(Atama ga itai desu.)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "あたまがいたいです。(Atama ga itai desu.)", isCorrect: true, order: 0 },
          { label: "B", text: "はながいたいです。(Hana ga itai desu.)", isCorrect: false, order: 1 },
          { label: "C", text: "おなかがいたいです。(Onaka ga itai desu.)", isCorrect: false, order: 2 },
          { label: "D", text: "のどがいたいです。(Nodo ga itai desu.)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Số điện thoại cấp cứu y tế (救急車 - Kyūkyūsha) tại Nhật Bản là số mấy?",
        correctAnswer: "119 (Một một chín)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "119 (Một một chín)", isCorrect: true, order: 0 },
          { label: "B", text: "110 (Một một không) — Cảnh sát", isCorrect: false, order: 1 },
          { label: "C", text: "911 (Chín một một) — Mỹ", isCorrect: false, order: 2 },
          { label: "D", text: "115 (Một một năm)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "PHRASE",
        question: "Tại nhà thuốc, để xin 'thuốc hạ sốt', bạn nói gì?",
        correctAnswer: "げねつざいをください。(Genetsuzai o kudasai.)",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "げねつざいをください。(Genetsuzai o kudasai.)", isCorrect: true, order: 0 },
          { label: "B", text: "くすりがほしいです。(Kusuri ga hoshii desu.)", isCorrect: false, order: 1 },
          { label: "C", text: "いたみどめをください。(Itamidome o kudasai.)", isCorrect: false, order: 2 },
          { label: "D", text: "びょういんにいきたい。(Byōin ni ikitai.)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "CULTURE",
        question: "Khi bị ốm ở Nhật và đến bệnh viện, điều quan trọng nào cần chuẩn bị?",
        correctAnswer: "Thẻ bảo hiểm y tế (健康保険証 - Kenkō Hoken-shō) và thẻ ngoại kiều (在留カード)",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "Thẻ bảo hiểm y tế (健康保険証 - Kenkō Hoken-shō) và thẻ ngoại kiều (在留カード)", isCorrect: true, order: 0 },
          { label: "B", text: "Chỉ cần hộ chiếu (パスポート)", isCorrect: false, order: 1 },
          { label: "C", text: "Không cần giấy tờ gì, Nhật phục vụ miễn phí", isCorrect: false, order: 2 },
          { label: "D", text: "Cần visa du lịch và giấy xác nhận khách sạn", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "at-konbini-convenience-store",
    title: "Bài Học 21: Mua Sắm Tại Cửa Hàng Tiện Lợi (Konbini)",
    description: "Học cách giao tiếp, hâm nóng cơm hộp bento, xin túi nilon và thanh toán tại 7-Eleven, Lawson, FamilyMart.",
    level: "N5",
    order: 20,
    xpReward: 130,
    exercises: [
      {
        type: "PHRASE",
        question: "Nhân viên Konbini hỏi: 'お弁当温めますか？' (Obentō atatamemasu ka?). Câu này có nghĩa là gì?",
        correctAnswer: "Quý khách có muốn hâm nóng hộp cơm không ạ?",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "Quý khách có muốn hâm nóng hộp cơm không ạ?", isCorrect: true, order: 0 },
          { label: "B", text: "Quý khách có cần túi đựng không ạ?", isCorrect: false, order: 1 },
          { label: "C", text: "Quý khách thanh toán bằng tiền mặt hay thẻ?", isCorrect: false, order: 2 },
          { label: "D", text: "Quý khách có thẻ tích điểm không ạ?", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "PHRASE",
        question: "Nếu muốn nhờ nhân viên hâm nóng cơm hộp, bạn trả lời thế nào?",
        correctAnswer: "はい、お願いします。(Hai, onegaishimasu.)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "はい、お願いします。(Hai, onegaishimasu.)", isCorrect: true, order: 0 },
          { label: "B", text: "いいえ、けっこうです。(Iie, kekkou desu.)", isCorrect: false, order: 1 },
          { label: "C", text: "温めません。(Atatamemasen.)", isCorrect: false, order: 2 },
          { label: "D", text: "ごちそうさまでした。(Gochisousama deshita.)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Từ 'túi nilon' trong tiếng Nhật thường dùng tại quầy thu ngân là gì?",
        correctAnswer: "レジ袋 (Reji-bukuro)",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "レジ袋 (Reji-bukuro)", isCorrect: true, order: 0 },
          { label: "B", text: "かばん (Kaban)", isCorrect: false, order: 1 },
          { label: "C", text: "さいふ (Saifu)", isCorrect: false, order: 2 },
          { label: "D", text: "はこ (Hako)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "CULTURE",
        question: "Để từ chối túi nilon một cách lịch sự, người Nhật thường nói gì?",
        correctAnswer: "袋は大丈夫です。(Fukuro wa daijoubu desu.)",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "袋は大丈夫です。(Fukuro wa daijoubu desu.)", isCorrect: true, order: 0 },
          { label: "B", text: "袋をください。(Fukuro o kudasai.)", isCorrect: false, order: 1 },
          { label: "C", text: "袋がいります。(Fukuro ga irimasu.)", isCorrect: false, order: 2 },
          { label: "D", text: "袋を捨ててください。(Fukuro o sutete kudasai.)", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "tokyo-metro-directions",
    title: "Bài Học 22: Hỏi Đường & Đi Tàu Điện Ngầm Tokyo",
    description: "Luyện cách hỏi đường, mua vé tàu, xác nhận cửa ra (Exit) và chuyến tàu Shinkansen.",
    level: "N5",
    order: 21,
    xpReward: 140,
    exercises: [
      {
        type: "PHRASE",
        question: "Muốn hỏi 'Tàu điện đi Tokyo đi từ sân ga số mấy?', bạn hỏi câu nào?",
        correctAnswer: "東京行きは何番線ですか？ (Tōkyō-yuki wa nan-bansen desu ka?)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "東京行きは何番線ですか？ (Tōkyō-yuki wa nan-bansen desu ka?)", isCorrect: true, order: 0 },
          { label: "B", text: "東京はどこですか？ (Tōkyō wa doko desu ka?)", isCorrect: false, order: 1 },
          { label: "C", text: "切符はいくらですか？ (Kippu wa ikura desu ka?)", isCorrect: false, order: 2 },
          { label: "D", text: "何時に着きますか？ (Nan-ji ni tsukimasu ka?)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Biển chỉ dẫn 'Cửa ra' tại các nhà ga Nhật Bản được viết bằng chữ Hán nào?",
        correctAnswer: "出口 (Deguchi)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "出口 (Deguchi)", isCorrect: true, order: 0 },
          { label: "B", text: "入口 (Iriguchi)", isCorrect: false, order: 1 },
          { label: "C", text: "改札口 (Kaisatsuguchi)", isCorrect: false, order: 2 },
          { label: "D", text: "非常口 (Hijōguchi)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "PHRASE",
        question: "Khi bị lạc đường và muốn hỏi 'Đến đền Senso-ji đi như thế nào?', bạn nói:",
        correctAnswer: "浅草寺へはどう行けばいいですか？ (Sensō-ji e wa dō ikeba ii desu ka?)",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "浅草寺へはどう行けばいいですか？ (Sensō-ji e wa dō ikeba ii desu ka?)", isCorrect: true, order: 0 },
          { label: "B", text: "浅草寺はきれいですか？ (Sensō-ji wa kirei desu ka?)", isCorrect: false, order: 1 },
          { label: "C", text: "浅草寺に行きました。(Sensō-ji ni ikimashita.)", isCorrect: false, order: 2 },
          { label: "D", text: "浅草寺を見たいです。(Sensō-ji o mitai desu.)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "CULTURE",
        question: "Thẻ IC nạp tiền thông minh dùng để quẹt qua cửa soát vé tàu điện ở Tokyo tên là gì?",
        correctAnswer: "Suica hoặc Pasmo",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "Suica hoặc Pasmo", isCorrect: true, order: 0 },
          { label: "B", text: "Visa hoặc Mastercard", isCorrect: false, order: 1 },
          { label: "C", text: "JR Rail Pass giấy", isCorrect: false, order: 2 },
          { label: "D", text: "Shinkansen Card", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "onsen-hotsprings-etiquette",
    title: "Bài Học 23: Trải Nghiệm Suối Nước Nóng Onsen & Ryokan",
    description: "Khám phá văn hóa tắm khoáng nóng Onsen, quy tắc ứng xử và nghỉ đêm tại Ryokan truyền thống.",
    level: "N5",
    order: 22,
    xpReward: 140,
    exercises: [
      {
        type: "CULTURE",
        question: "Quy tắc quan trọng nhất TRƯỚC KHI bước vào bồn tắm Onsen là gì?",
        correctAnswer: "Phải tắm gội rửa sạch sẽ toàn thân tại khu vực tắm vòi trước khi xuống bồn ngâm",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "Phải tắm gội rửa sạch sẽ toàn thân tại khu vực tắm vòi trước khi xuống bồn ngâm", isCorrect: true, order: 0 },
          { label: "B", text: "Mặc đồ bơi hoặc quấn khăn tắm nhảy ngay xuống bồn", isCorrect: false, order: 1 },
          { label: "C", text: "Mang đồ ăn và nước uống xuống ngâm cùng", isCorrect: false, order: 2 },
          { label: "D", text: "Bơi lội và lặn ngụp thoải mái trong bồn khoáng", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Bộ áo choàng truyền thống bằng vải cotton mặc khi nghỉ ngơi tại Onsen và Ryokan là gì?",
        correctAnswer: "浴衣 (Yukata)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "浴衣 (Yukata)", isCorrect: true, order: 0 },
          { label: "B", text: "着物 (Kimono)", isCorrect: false, order: 1 },
          { label: "C", text: "袴 (Hakama)", isCorrect: false, order: 2 },
          { label: "D", text: "甚平 (Jinbei)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "PHRASE",
        question: "Để khen ngợi 'Nước nóng thật sảng khoái và dễ chịu!', bạn nói câu nào?",
        correctAnswer: "とても気持ちがいいです！ (Totemo kimochi ga ii desu!)",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "とても気持ちがいいです！ (Totemo kimochi ga ii desu!)", isCorrect: true, order: 0 },
          { label: "B", text: "とても熱すぎます。(Totemo atsusugimasu.)", isCorrect: false, order: 1 },
          { label: "C", text: "お腹が空きました。(Onaka ga sukimashita.)", isCorrect: false, order: 2 },
          { label: "D", text: "寒くなりました。(Samuku narimashita.)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "CULTURE",
        question: "Trước cửa phòng tắm Onsen thường treo rèm Noren có chữ gì để chỉ suối nước nóng?",
        correctAnswer: "Ký tự 'ゆ' (Yu - nước nóng)",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "Ký tự 'ゆ' (Yu - nước nóng)", isCorrect: true, order: 0 },
          { label: "B", text: "Ký tự '水' (Mizu - nước lạnh)", isCorrect: false, order: 1 },
          { label: "C", text: "Ký tự '茶' (Cha - trà)", isCorrect: false, order: 2 },
          { label: "D", text: "Ký tự '酒' (Sake - rượu)", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "seasons-weather-matsuri",
    title: "Bài Học 24: Thời Tiết, Bốn Mùa & Lễ Hội Matsuri",
    description: "Học từ vựng về thời tiết, 4 mùa Xuân Hạ Thu Đông và các lễ hội truyền thống rực rỡ sắc màu.",
    level: "N5",
    order: 23,
    xpReward: 150,
    exercises: [
      {
        type: "VOCABULARY",
        question: "Bốn mùa 'Xuân - Hạ - Thu - Đông' trong tiếng Nhật đọc lần lượt là gì?",
        correctAnswer: "Haru (春) - Natsu (夏) - Aki (秋) - Fuyu (冬)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "Haru (春) - Natsu (夏) - Aki (秋) - Fuyu (冬)", isCorrect: true, order: 0 },
          { label: "B", text: "Natsu - Haru - Fuyu - Aki", isCorrect: false, order: 1 },
          { label: "C", text: "Aki - Fuyu - Haru - Natsu", isCorrect: false, order: 2 },
          { label: "D", text: "Fuyu - Aki - Natsu - Haru", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "PHRASE",
        question: "Khi trời bắt đầu đổ mưa rào, bạn diễn đạt câu nào?",
        correctAnswer: "雨が降ってきました。(Ame ga futte kimashita.)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "雨が降ってきました。(Ame ga futte kimashita.)", isCorrect: true, order: 0 },
          { label: "B", text: "雪が降っています。(Yuki ga futte imasu.)", isCorrect: false, order: 1 },
          { label: "C", text: "風が強いです。(Kaze ga tsuyoi desu.)", isCorrect: false, order: 2 },
          { label: "D", text: "晴れています。(Harete imasu.)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "CULTURE",
        question: "Hoạt động ngắm hoa anh đào nở vào mùa xuân của người Nhật được gọi là gì?",
        correctAnswer: "花見 (Hanami)",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "花見 (Hanami)", isCorrect: true, order: 0 },
          { label: "B", text: "月見 (Tsukimi)", isCorrect: false, order: 1 },
          { label: "C", text: "紅葉狩り (Momijigari)", isCorrect: false, order: 2 },
          { label: "D", text: "花火大会 (Hanabi Taikai)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "VOCABULARY",
        question: "Từ 'Pháo hoa' thắp sáng bầu trời đêm lễ hội mùa hè Nhật Bản là gì?",
        correctAnswer: "花火 (Hanabi)",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "花火 (Hanabi)", isCorrect: true, order: 0 },
          { label: "B", text: "火事 (Kaji)", isCorrect: false, order: 1 },
          { label: "C", text: "焚き火 (Takibi)", isCorrect: false, order: 2 },
          { label: "D", text: "灯籠 (Tōrō)", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
  {
    slug: "n5-comprehensive-mastery",
    title: "Bài Học 25: Thử Thách Đỉnh Cao — Tốt Nghiệp N5 JLPT",
    description: "Bài kiểm tra tổng hợp toàn diện kiểm tra ngữ pháp, trợ từ, kính ngữ và phản xạ giao tiếp N5.",
    level: "N5",
    order: 24,
    xpReward: 200,
    exercises: [
      {
        type: "GRAMMAR",
        question: "Điền trợ từ thích hợp: 私はバス ( ? ) 会社へ行きます。",
        correctAnswer: "で (Chỉ phương tiện di chuyển)",
        points: 10,
        order: 0,
        options: [
          { label: "A", text: "で (Chỉ phương tiện di chuyển)", isCorrect: true, order: 0 },
          { label: "B", text: "に (Chỉ hướng đến)", isCorrect: false, order: 1 },
          { label: "C", text: "を (Chỉ tân ngữ)", isCorrect: false, order: 2 },
          { label: "D", text: "へ (Chỉ phương hướng)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "GRAMMAR",
        question: "Chọn câu đúng nhất mang nghĩa: 'Làm ơn hãy bật điều hòa giúp tôi':",
        correctAnswer: "エアコンをつけてください。(Eakon o tsukete kudasai.)",
        points: 10,
        order: 1,
        options: [
          { label: "A", text: "エアコンをつけてください。(Eakon o tsukete kudasai.)", isCorrect: true, order: 0 },
          { label: "B", text: "エアコンを消してください。(Eakon o keshite kudasai.)", isCorrect: false, order: 1 },
          { label: "C", text: "エアコンを開けてください。(Eakon o akete kudasai.)", isCorrect: false, order: 2 },
          { label: "D", text: "エアコンを閉めてください。(Eakon o shimete kudasai.)", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "READING",
        question: "Đọc đoạn văn sau: '昨日は日曜日でした。天気がよかったので、公園で本を読みました。' Người nói đã làm gì hôm qua?",
        correctAnswer: "Vì thời tiết đẹp nên đã đọc sách ở công viên",
        points: 10,
        order: 2,
        options: [
          { label: "A", text: "Vì thời tiết đẹp nên đã đọc sách ở công viên", isCorrect: true, order: 0 },
          { label: "B", text: "Vì trời mưa nên ở nhà đọc sách", isCorrect: false, order: 1 },
          { label: "C", text: "Đi làm bài tập ở công viên", isCorrect: false, order: 2 },
          { label: "D", text: "Đi mua sách mới vào ngày chủ nhật", isCorrect: false, order: 3 },
        ],
      },
      {
        type: "CAPSTONE",
        question: "Chúc mừng bạn đã hoàn thành trọn vẹn 25 bài học N5! Câu khẩu hiệu động viên tiếng Nhật nổi tiếng là gì?",
        correctAnswer: "がんばってください！(Ganbatte kudasai! - Cố gắng lên nhé!)",
        points: 10,
        order: 3,
        options: [
          { label: "A", text: "がんばってください！(Ganbatte kudasai! - Cố gắng lên nhé!)", isCorrect: true, order: 0 },
          { label: "B", text: "お疲れ様でした。(Otsukaresama deshita.)", isCorrect: false, order: 1 },
          { label: "C", text: "失礼します。(Shitsurei shimasu.)", isCorrect: false, order: 2 },
          { label: "D", text: "お邪魔します。(Ojamashimasu.)", isCorrect: false, order: 3 },
        ],
      },
    ],
  },
];
