import { SeedKanji, SeedVocab } from "./kanji-vocab";

// ─────────────────────────────────────────────────────────────────────────────
// JLPT N4 KANJI SEED DATA
// ─────────────────────────────────────────────────────────────────────────────
export const KANJI_N4: SeedKanji[] = [
  { character: "会", meaning: "Gặp gỡ, Hội (Hội)", strokeCount: 6, jlptLevel: "N4", readings: [{ reading: "カイ", type: "ONYOMI" }, { reading: "あ・う", type: "KUNYOMI" }] },
  { character: "社", meaning: "Công ty, Đền thờ (Xã)", strokeCount: 7, jlptLevel: "N4", readings: [{ reading: "シャ", type: "ONYOMI" }, { reading: "やしろ", type: "KUNYOMI" }] },
  { character: "店", meaning: "Cửa hàng, Tiệm (Điếm)", strokeCount: 8, jlptLevel: "N4", readings: [{ reading: "テン", type: "ONYOMI" }, { reading: "みせ", type: "KUNYOMI" }] },
  { character: "駅", meaning: "Nhà ga (Dịch)", strokeCount: 14, jlptLevel: "N4", readings: [{ reading: "エキ", type: "ONYOMI" }] },
  { character: "校", meaning: "Trường học (Hiệu)", strokeCount: 10, jlptLevel: "N4", readings: [{ reading: "コウ", type: "ONYOMI" }] },
  { character: "勉", meaning: "Cố gắng, Nỗ lực (Miễn)", strokeCount: 10, jlptLevel: "N4", readings: [{ reading: "ベン", type: "ONYOMI" }, { reading: "つと・める", type: "KUNYOMI" }] },
  { character: "強", meaning: "Mạnh mẽ, Khỏe (Cường)", strokeCount: 11, jlptLevel: "N4", readings: [{ reading: "キョウ", type: "ONYOMI" }, { reading: "つよ・い", type: "KUNYOMI" }] },
  { character: "電", meaning: "Điện (Điện)", strokeCount: 13, jlptLevel: "N4", readings: [{ reading: "デン", type: "ONYOMI" }] },
  { character: "車", meaning: "Xe hơi, Xe cộ (Xa)", strokeCount: 7, jlptLevel: "N4", readings: [{ reading: "シャ", type: "ONYOMI" }, { reading: "くるま", type: "KUNYOMI" }] },
  { character: "旅", meaning: "Du lịch, Chuyến đi (Lữ)", strokeCount: 10, jlptLevel: "N4", readings: [{ reading: "リョ", type: "ONYOMI" }, { reading: "たび", type: "KUNYOMI" }] },
  { character: "館", meaning: "Tòa nhà, Khách quán (Quán)", strokeCount: 16, jlptLevel: "N4", readings: [{ reading: "カン", type: "ONYOMI" }, { reading: "やかた", type: "KUNYOMI" }] },
  { character: "宿", meaning: "Nhà trọ, Chỗ ở (Túc)", strokeCount: 11, jlptLevel: "N4", readings: [{ reading: "シュク", type: "ONYOMI" }, { reading: "やど", type: "KUNYOMI" }] },
  { character: "題", meaning: "Đề tài, Câu hỏi (Đề)", strokeCount: 18, jlptLevel: "N4", readings: [{ reading: "ダイ", type: "ONYOMI" }] },
  { character: "考", meaning: "Suy nghĩ, Cân nhắc (Khảo)", strokeCount: 6, jlptLevel: "N4", readings: [{ reading: "コウ", type: "ONYOMI" }, { reading: "かんが・える", type: "KUNYOMI" }] },
  { character: "運", meaning: "Vận chuyển, May mắn (Vận)", strokeCount: 12, jlptLevel: "N4", readings: [{ reading: "ウン", type: "ONYOMI" }, { reading: "はこ・ぶ", type: "KUNYOMI" }] },
  { character: "動", meaning: "Chuyển động, Hoạt động (Động)", strokeCount: 11, jlptLevel: "N4", readings: [{ reading: "ドウ", type: "ONYOMI" }, { reading: "うご・く", type: "KUNYOMI" }] },
  { character: "族", meaning: "Gia tộc, Bộ tộc (Tộc)", strokeCount: 11, jlptLevel: "N4", readings: [{ reading: "ゾク", type: "ONYOMI" }] },
  { character: "貸", meaning: "Cho mượn, Cho vay (Thải)", strokeCount: 12, jlptLevel: "N4", readings: [{ reading: "タイ", type: "ONYOMI" }, { reading: "か・す", type: "KUNYOMI" }] },
  { character: "借", meaning: "Mượn, Vay (Tá)", strokeCount: 10, jlptLevel: "N4", readings: [{ reading: "シャク", type: "ONYOMI" }, { reading: "か・りる", type: "KUNYOMI" }] },
  { character: "明", meaning: "Sáng sủa, Rõ ràng (Minh)", strokeCount: 8, jlptLevel: "N4", readings: [{ reading: "メイ", type: "ONYOMI" }, { reading: "あか・るい", type: "KUNYOMI" }] },
  { character: "暗", meaning: "Tối tăm (Ám)", strokeCount: 13, jlptLevel: "N4", readings: [{ reading: "アン", type: "ONYOMI" }, { reading: "くら・い", type: "KUNYOMI" }] },
  { character: "楽", meaning: "Vui vẻ, Âm nhạc (Lạc/Nhạc)", strokeCount: 13, jlptLevel: "N4", readings: [{ reading: "ラク", type: "ONYOMI" }, { reading: "たの・しい", type: "KUNYOMI" }] },
  { character: "歌", meaning: "Bài hát, Ca hát (Ca)", strokeCount: 14, jlptLevel: "N4", readings: [{ reading: "カ", type: "ONYOMI" }, { reading: "うた", type: "KUNYOMI" }] },
  { character: "質", meaning: "Chất lượng, Hỏi (Chất)", strokeCount: 15, jlptLevel: "N4", readings: [{ reading: "シツ", type: "ONYOMI" }] },
  { character: "問", meaning: "Hỏi han, Câu hỏi (Vấn)", strokeCount: 11, jlptLevel: "N4", readings: [{ reading: "モン", type: "ONYOMI" }, { reading: "と・う", type: "KUNYOMI" }] },
  { character: "答", meaning: "Trả lời, Đáp án (Đáp)", strokeCount: 12, jlptLevel: "N4", readings: [{ reading: "トウ", type: "ONYOMI" }, { reading: "こた・える", type: "KUNYOMI" }] },
  { character: "開", meaning: "Mở ra, Khởi đầu (Khai)", strokeCount: 12, jlptLevel: "N4", readings: [{ reading: "カイ", type: "ONYOMI" }, { reading: "あ・ける", type: "KUNYOMI" }, { reading: "ひら・く", type: "KUNYOMI" }] },
  { character: "閉", meaning: "Đóng lại (Bế)", strokeCount: 11, jlptLevel: "N4", readings: [{ reading: "ヘイ", type: "ONYOMI" }, { reading: "し・める", type: "KUNYOMI" }, { reading: "と・じる", type: "KUNYOMI" }] },
  { character: "始", meaning: "Bắt đầu (Thủy)", strokeCount: 8, jlptLevel: "N4", readings: [{ reading: "シ", type: "ONYOMI" }, { reading: "はじ・まる", type: "KUNYOMI" }, { reading: "はじ・める", type: "KUNYOMI" }] },
  { character: "終", meaning: "Kết thúc (Chung)", strokeCount: 11, jlptLevel: "N4", readings: [{ reading: "シュウ", type: "ONYOMI" }, { reading: "お・わる", type: "KUNYOMI" }] },
];

// ─────────────────────────────────────────────────────────────────────────────
// JLPT N4 VOCABULARY SEED DATA
// ─────────────────────────────────────────────────────────────────────────────
export const VOCABULARY_N4: SeedVocab[] = [
  {
    word: "会社員",
    kana: "かいしゃいん",
    kanji: "会社員",
    romaji: "kaishain",
    meaning: "Nhân viên công ty",
    partOfSpeech: "noun",
    jlptLevel: "N4",
    exampleJapanese: "田中さんは日本の会社員です。",
    exampleRomaji: "Tanaka-san wa Nihon no kaishain desu.",
    exampleMeaning: "Anh Tanaka là nhân viên một công ty Nhật Bản.",
  },
  {
    word: "案内する",
    kana: "あんないする",
    kanji: "案内する",
    romaji: "annai suru",
    meaning: "Hướng dẫn, dẫn đường",
    partOfSpeech: "verb",
    jlptLevel: "N4",
    exampleJapanese: "京都の街をご案内します。",
    exampleRomaji: "Kyōto no machi o go-annai shimasu.",
    exampleMeaning: "Tôi sẽ hướng dẫn bạn tham quan phố phường Kyoto.",
  },
  {
    word: "準備",
    kana: "じゅんび",
    kanji: "準備",
    romaji: "junbi",
    meaning: "Sự chuẩn bị",
    partOfSpeech: "noun",
    jlptLevel: "N4",
    exampleJapanese: "旅行の準備ができましたか？",
    exampleRomaji: "Ryokō no junbi ga dekimashita ka?",
    exampleMeaning: "Bạn đã chuẩn bị xong cho chuyến du lịch chưa?",
  },
  {
    word: "説明する",
    kana: "せつめいする",
    kanji: "説明する",
    romaji: "setsumei suru",
    meaning: "Giải thích, thuyết minh",
    partOfSpeech: "verb",
    jlptLevel: "N4",
    exampleJapanese: "使い道を詳しく説明してください。",
    exampleRomaji: "Tsukaimichi o kuwashiku setsumei shite kudasai.",
    exampleMeaning: "Xin vui lòng giải thích chi tiết cách sử dụng.",
  },
  {
    word: "連絡する",
    kana: "れんらくする",
    kanji: "連絡する",
    romaji: "renraku suru",
    meaning: "Liên lạc, thông báo",
    partOfSpeech: "verb",
    jlptLevel: "N4",
    exampleJapanese: "明日、メールで連絡します。",
    exampleRomaji: "Ashita, mēru de renraku shimasu.",
    exampleMeaning: "Ngày mai tôi sẽ liên lạc qua email.",
  },
  {
    word: "遠慮する",
    kana: "えんりょする",
    kanji: "遠慮する",
    romaji: "enryo suru",
    meaning: "Ngại ngùng, kiêng nể",
    partOfSpeech: "verb",
    jlptLevel: "N4",
    exampleJapanese: "どうぞ遠慮しないで召し上がってください。",
    exampleRomaji: "Dōzo enryo shinaide meshiagatte kudasai.",
    exampleMeaning: "Xin cứ tự nhiên dùng bữa, đừng ngại ngùng nhé.",
  },
  {
    word: "都合",
    kana: "つごう",
    kanji: "都合",
    romaji: "tsugō",
    meaning: "Điều kiện thuận tiện, lịch trình",
    partOfSpeech: "noun",
    jlptLevel: "N4",
    exampleJapanese: "今週の土曜日は都合がいいですか？",
    exampleRomaji: "Konshū no doyōbi wa tsugō ga ii desu ka?",
    exampleMeaning: "Thứ Bảy tuần này bạn có tiện thời gian không?",
  },
  {
    word: "複雑",
    kana: "ふくざつ",
    kanji: "複雑",
    romaji: "fukuzatsu",
    meaning: "Phức tạp, rắc rối",
    partOfSpeech: "adjective",
    jlptLevel: "N4",
    exampleJapanese: "この駅の出口はとても複雑です。",
    exampleRomaji: "Kono eki no deguchi wa totemo fukuzatsu desu.",
    exampleMeaning: "Lối ra của ga này rất phức tạp.",
  },
  {
    word: "簡単",
    kana: "かんたん",
    kanji: "簡単",
    romaji: "kantan",
    meaning: "Đơn giản, dễ dàng",
    partOfSpeech: "adjective",
    jlptLevel: "N4",
    exampleJapanese: "このアプリは使い方が簡単です。",
    exampleRomaji: "Kono apuri wa tsukaikata ga kantan desu.",
    exampleMeaning: "Ứng dụng này có cách sử dụng rất đơn giản.",
  },
  {
    word: "必ず",
    kana: "かならず",
    kanji: "必ず",
    romaji: "kanarazu",
    meaning: "Nhất định, chắc chắn",
    partOfSpeech: "adverb",
    jlptLevel: "N4",
    exampleJapanese: "約束は必ず守ります。",
    exampleRomaji: "Yakusoku wa kanarazu mamorimasu.",
    exampleMeaning: "Tôi nhất định sẽ giữ lời hứa.",
  },
  {
    word: "約束",
    kana: "やくそく",
    kanji: "約束",
    romaji: "yakusoku",
    meaning: "Lời hứa, cuộc hẹn",
    partOfSpeech: "noun",
    jlptLevel: "N4",
    exampleJapanese: "友達と映画を見る約束があります。",
    exampleRomaji: "Tomodachi to eiga o miru yakusoku ga arimasu.",
    exampleMeaning: "Tôi có hẹn đi xem phim với bạn.",
  },
  {
    word: "習慣",
    kana: "しゅうかん",
    kanji: "習慣",
    romaji: "shūkan",
    meaning: "Tập quán, thói quen",
    partOfSpeech: "noun",
    jlptLevel: "N4",
    exampleJapanese: "靴を脱ぐのは日本の習慣です。",
    exampleRomaji: "Kutsu o nugu no wa Nihon no shūkan desu.",
    exampleMeaning: "Cởi giày trước khi vào nhà là tập quán của người Nhật.",
  },
  {
    word: "故障",
    kana: "こしょう",
    kanji: "故障",
    romaji: "koshō",
    meaning: "Hỏng hóc, sự cố máy móc",
    partOfSpeech: "noun",
    jlptLevel: "N4",
    exampleJapanese: "エレベーターが故障しています。",
    exampleRomaji: "Erebētā ga koshō shite imasu.",
    exampleMeaning: "Thang máy đang bị hỏng.",
  },
  {
    word: "修理する",
    kana: "しゅうりする",
    kanji: "修理する",
    romaji: "shūri suru",
    meaning: "Sửa chữa",
    partOfSpeech: "verb",
    jlptLevel: "N4",
    exampleJapanese: "自転車を修理してもらいました。",
    exampleRomaji: "Jitensha o shūri shite moraimashita.",
    exampleMeaning: "Tôi đã nhờ sửa xe đạp giúp.",
  },
  {
    word: "経験",
    kana: "けいけん",
    kanji: "経験",
    romaji: "keiken",
    meaning: "Kinh nghiệm, trải nghiệm",
    partOfSpeech: "noun",
    jlptLevel: "N4",
    exampleJapanese: "日本でアルバイトの経験があります。",
    exampleRomaji: "Nihon de arubaito no keiken ga arimasu.",
    exampleMeaning: "Tôi đã có kinh nghiệm làm thêm tại Nhật Bản.",
  },
  {
    word: "趣味",
    kana: "しゅみ",
    kanji: "趣味",
    romaji: "shumi",
    meaning: "Sở thích",
    partOfSpeech: "noun",
    jlptLevel: "N4",
    exampleJapanese: "私の趣味は写真を撮ることです。",
    exampleRomaji: "Watashi no shumi wa shashin o toru koto desu.",
    exampleMeaning: "Sở thích của tôi là chụp ảnh phong cảnh.",
  },
  {
    word: "合格する",
    kana: "ごうかくする",
    kanji: "合格する",
    romaji: "gōkaku suru",
    meaning: "Đỗ, thi đậu",
    partOfSpeech: "verb",
    jlptLevel: "N4",
    exampleJapanese: "JLPT N4の試験に合格しました！",
    exampleRomaji: "JLPT N4 no shiken ni gōkaku shimashita!",
    exampleMeaning: "Tôi đã thi đỗ kỳ thi JLPT N4 rồi!",
  },
  {
    word: "心配する",
    kana: "しんぱいする",
    kanji: "心配する",
    romaji: "shinpai suru",
    meaning: "Lo lắng, bận tâm",
    partOfSpeech: "verb",
    jlptLevel: "N4",
    exampleJapanese: "何も心配しないでください。",
    exampleRomaji: "Nanimo shinpai shinaide kudasai.",
    exampleMeaning: "Xin đừng lo lắng về điều gì cả.",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// JLPT N4 GRAMMAR SEED DATA
// ─────────────────────────────────────────────────────────────────────────────
export const GRAMMAR_N4 = [
  {
    title: "〜てしまう (te shimau)",
    level: "N4",
    meaning: "Lỡ làm... / Làm xong toàn bộ một hành động (mang sắc thái tiếc nuối hoặc hoàn tất)",
    structure: "Động từ thể て + しまう / しまいました (Dạng nói: 〜ちゃう / 〜ちゃった)",
    commonMistakes: "Thường dùng để biểu thị sự hối tiếc ngoài ý muốn. Khi nói chuyện thường ngày chuyển thành ちゃう (食べちゃう).",
    examples: [
      { japanese: "パスポートを忘れてしまいました。", romaji: "Pasupōto o wasurete shimaimashita.", meaning: "Tôi lỡ để quên hộ chiếu mất rồi." },
      { japanese: "宿題を全部やってしまいました。", romaji: "Shukudai o zenbu yatte shimaimashita.", meaning: "Tôi đã hoàn thành xong toàn bộ bài tập." },
    ],
  },
  {
    title: "〜ば (Thể điều kiện - Thể Ba)",
    level: "N4",
    meaning: "Nếu... thì... (Điều kiện tất yếu hoặc giả định)",
    structure: "Động từ nhóm 1: đổi âm u -> e + ば | Nhóm 2: bỏ る + れば | Tính từ -i: đổi い -> ければ",
    commonMistakes: "Khác với たら (chỉ dùng sau khi hành động 1 xảy ra), thể ば nhấn mạnh vào điều kiện tiền đề 'Nếu có A thì mới có B'.",
    examples: [
      { japanese: "安ければ買います。", romaji: "Yasukereba kaimasu.", meaning: "Nếu rẻ thì tôi sẽ mua." },
      { japanese: "練習すれば上手になります。", romaji: "Renshū sureba jōzu ni narimasu.", meaning: "Nếu chịu khó luyện tập thì sẽ giỏi lên." },
    ],
  },
  {
    title: "〜たら (tara)",
    level: "N4",
    meaning: "Nếu... / Sau khi... thì... (Điều kiện giả định tổng quát và phổ biến nhất)",
    structure: "Động từ thể Quá khứ (た) + ら",
    commonMistakes: "たら dùng được cho cả câu mời rủ, mệnh lệnh, nhờ vả ở vế sau, trong khi と và ば không dùng được.",
    examples: [
      { japanese: "雨が降ったら行きません。", romaji: "Ame ga futtara ikimasen.", meaning: "Nếu trời mưa thì tôi sẽ không đi." },
      { japanese: "駅に着いたら電話してください。", romaji: "Eki ni tsuitara denwa shite kudasai.", meaning: "Sau khi đến ga thì hãy gọi cho tôi nhé." },
    ],
  },
  {
    title: "〜なら (nara)",
    level: "N4",
    meaning: "Nếu là... / Nếu nói về... (Đưa ra lời khuyên hoặc tiếp nhận chủ đề người khác nói)",
    structure: "[Danh từ / Thể thông thường] + なら",
    commonMistakes: "Dùng khi tiếp nhận thông tin từ đối phương và đưa ra lời khuyên hoặc phương án phù hợp.",
    examples: [
      { japanese: "日本料理なら寿司が一番好きです。", romaji: "Nihon ryōri nara sushi ga ichiban suki desu.", meaning: "Nếu là món ăn Nhật thì tôi thích nhất sushi." },
      { japanese: "京都へ行くなら秋がおすすめです。", romaji: "Kyōto e iku nara aki ga osusume desu.", meaning: "Nếu bạn đi Kyoto thì mùa thu là thời điểm đẹp nhất." },
    ],
  },
  {
    title: "〜受身 (Thể bị động - Ukemi)",
    level: "N4",
    meaning: "Bị / Được tác động bởi ai đó (Nhận hành động)",
    structure: "Nhóm 1: âm u -> a + れる | Nhóm 2: bỏ る + られる | くる -> こられる | する -> される",
    commonMistakes: "Người thực hiện hành động được đánh dấu bằng trợ từ に (Ví dụ: 先生に褒められた).",
    examples: [
      { japanese: "先生に褒められました。", romaji: "Sensei ni homeraremashita.", meaning: "Tôi đã được thầy giáo khen ngợi." },
      { japanese: "雨に降られて服が濡れました。", romaji: "Ame ni furarete fuku ga nuremashita.", meaning: "Bị dính mưa nên quần áo ướt sũng." },
    ],
  },
  {
    title: "〜使役 (Thể sai khiến - Shieki)",
    level: "N4",
    meaning: "Bắt / Cho phép ai đó làm gì",
    structure: "Nhóm 1: âm u -> a + せる | Nhóm 2: bỏ る + させる | くる -> こさせる | する -> させる",
    commonMistakes: "Khi xin phép lịch sự cho bản thân làm việc gì: dùng 使役 + ていただけませんか (Ví dụ: 休ませていただけませんか).",
    examples: [
      { japanese: "お母さんは子供に野菜を食べさせます。", romaji: "Okāsan wa kodomo ni yasai o tabesasemasu.", meaning: "Mẹ bắt con ăn rau củ." },
      { japanese: "少し休ませてください。", romaji: "Sukoshi yasumasete kudasai.", meaning: "Xin hãy cho phép tôi nghỉ ngơi một chút." },
    ],
  },
  {
    title: "〜やすい / 〜にくい",
    level: "N4",
    meaning: "Dễ làm gì... / Khó làm gì...",
    structure: "Động từ thể ます (bỏ ます) + やすい / にくい",
    commonMistakes: "Biến thành tính từ đuôi -i nên có thể chia phủ định là やすくない / にくくない.",
    examples: [
      { japanese: "このペンはとても書きやすいです。", romaji: "Kono pen wa totemo kakiyasui desu.", meaning: "Cây bút này viết rất trơn và dễ viết." },
      { japanese: "漢字は覚えにくいです。", romaji: "Kanji wa oboenikui desu.", meaning: "Chữ Hán thì khá khó nhớ." },
    ],
  },
  {
    title: "〜すぎる (sugiru)",
    level: "N4",
    meaning: "Quá... (Vượt quá mức độ bình thường, thường mang nghĩa tiêu cực)",
    structure: "Động từ bỏ ます / Tính từ -i bỏ い / Tính từ -na bỏ な + すぎる",
    commonMistakes: "Ví dụ: 食べすぎる (Ăn quá nhiều), 高すぎる (Quá đắt), 静かすぎる (Quá yên ắng).",
    examples: [
      { japanese: "昨夜お酒を飲みすぎました。", romaji: "Yūbe osake o nomisugimashita.", meaning: "Tối qua tôi đã uống quá nhiều rượu." },
      { japanese: "この問題は難しすぎます。", romaji: "Kono mondai wa muzukashisugimasu.", meaning: "Câu hỏi này khó quá mức." },
    ],
  },
  {
    title: "〜そうだ (Trông có vẻ - Phán đoán bề ngoài)",
    level: "N4",
    meaning: "Trông có vẻ... / Dường như sắp...",
    structure: "Động từ bỏ ます / Tính từ -i bỏ い / Tính từ -na + そうだ",
    commonMistakes: "Trường hợp đặc biệt: いい (Tốt) -> よさそうだ (Trông có vẻ tốt). Không dùng cho các thuộc tính nhìn thấy rõ (như 赤い -> không nói 赤そうだ).",
    examples: [
      { japanese: "このケーキは美味しそうです。", romaji: "Kono kēki wa oishisō desu.", meaning: "Chiếc bánh ngọt này trông có vẻ ngon thế." },
      { japanese: "今にも雨が降りそうです。", romaji: "Ima ni mo ame ga furisō desu.", meaning: "Trời trông như sắp đổ mưa đến nơi rồi." },
    ],
  },
  {
    title: "〜ておく (te oku)",
    level: "N4",
    meaning: "Làm sẵn... để chuẩn bị trước / Giữ nguyên trạng thái",
    structure: "Động từ thể て + おく (Dạng nói: 〜とく)",
    commonMistakes: "Thể hiện ý thức chuẩn bị chu đáo của người Nhật (Ví dụ: mua vé trước chuyến đi).",
    examples: [
      { japanese: "旅行の前にホテルを予約しておきます。", romaji: "Ryokō no mae ni hoteru o yoyaku shite okimasu.", meaning: "Trước chuyến du lịch tôi sẽ đặt sẵn phòng khách sạn." },
      { japanese: "窓を開けておいてください。", romaji: "Mado o akete oite kudasai.", meaning: "Xin hãy cứ để nguyên cửa sổ mở như thế." },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// JLPT N4 LESSONS & QUIZZES SEED DATA
// ─────────────────────────────────────────────────────────────────────────────
export const LESSONS_N4 = [
  {
    slug: "n4-lesson-01-daily-routine",
    title: "Bài 01 (N4): Biến Thể Động Từ & Thể Lỡ Lầm 〜てしまう",
    description: "Làm quen với cách diễn đạt sự nuối tiếc, hoàn tất công việc và các cấu trúc biến thể sơ trung cấp.",
    level: "N4",
    order: 0,
    xpReward: 35,
    exercises: [
      {
        type: "MULTIPLE_CHOICE",
        question: "Chọn câu đúng để diễn đạt: 'Tôi đã lỡ để quên ô trên tàu điện mất rồi.'",
        correctAnswer: "電車に傘を忘れてしまいました。",
        points: 10,
        options: [
          { text: "電車に傘を忘れてしまいました。", isCorrect: true },
          { text: "電車に傘を忘れましたです。", isCorrect: false },
          { text: "電車に傘を忘れることがあります。", isCorrect: false },
          { text: "電車に傘を忘れないでください。", isCorrect: false },
        ],
      },
      {
        type: "MULTIPLE_CHOICE",
        question: "Cấu trúc '〜やすい' được nối với dạng nào của động từ?",
        correctAnswer: "Động từ thể ます bỏ ます",
        points: 10,
        options: [
          { text: "Động từ thể ます bỏ ます", isCorrect: true },
          { text: "Động từ thể Từ điển (V-ru)", isCorrect: false },
          { text: "Động từ thể て", isCorrect: false },
          { text: "Động từ thể ない", isCorrect: false },
        ],
      },
    ],
  },
  {
    slug: "n4-lesson-02-conditions",
    title: "Bài 02 (N4): Nghệ Thuật Giả Định — ば, たら, なら & と",
    description: "Phân biệt sắc thái tinh tế giữa các dạng câu điều kiện trong giao tiếp đời sống Nhật Bản.",
    level: "N4",
    order: 1,
    xpReward: 35,
    exercises: [
      {
        type: "MULTIPLE_CHOICE",
        question: "Khi tiếp nhận thông tin từ người khác và khuyên 'Nếu là món Nhật thì sushi là số 1', ta dùng:",
        correctAnswer: "日本料理なら寿司が一番です。",
        points: 10,
        options: [
          { text: "日本料理なら寿司が一番です。", isCorrect: true },
          { text: "日本料理と寿司が一番です。", isCorrect: false },
          { text: "日本料理ば寿司が一番です。", isCorrect: false },
          { text: "日本料理て寿司が一番です。", isCorrect: false },
        ],
      },
    ],
  },
  {
    slug: "n4-lesson-03-passive-voice",
    title: "Bài 03 (N4): Thể Bị Động (受身) & Trợ Từ に Trong Giao Tiếp",
    description: "Học cách biểu đạt khi được khen ngợi hoặc khi gặp phiền phức do hoàn cảnh xung quanh tác động.",
    level: "N4",
    order: 2,
    xpReward: 40,
    exercises: [
      {
        type: "MULTIPLE_CHOICE",
        question: "Dạng bị động của động từ 褒めます (Khen ngợi) là gì?",
        correctAnswer: "褒められる",
        points: 10,
        options: [
          { text: "褒められる", isCorrect: true },
          { text: "褒めさせる", isCorrect: false },
          { text: "褒めすぎる", isCorrect: false },
          { text: "褒めやすい", isCorrect: false },
        ],
      },
    ],
  },
  {
    slug: "n4-lesson-04-causative",
    title: "Bài 04 (N4): Thể Sai Khiến & Mẫu Câu Xin Phép Lịch Sự",
    description: "Cấu trúc cho phép ai làm gì và mẫu câu xin phép đỉnh cao '〜させていただけませんか'.",
    level: "N4",
    order: 3,
    xpReward: 40,
    exercises: [
      {
        type: "MULTIPLE_CHOICE",
        question: "Câu xin phép 'Xin hãy cho phép tôi nghỉ phép ngày mai' nói lịch sự như thế nào?",
        correctAnswer: "明日休ませていただけませんか。",
        points: 10,
        options: [
          { text: "明日休ませていただけませんか。", isCorrect: true },
          { text: "明日休まないでください。", isCorrect: false },
          { text: "明日休みすぎます。", isCorrect: false },
          { text: "明日休むつもりです。", isCorrect: false },
        ],
      },
    ],
  },
  {
    slug: "n4-lesson-05-preparation",
    title: "Bài 05 (N4): Chuẩn Bị Trước 〜ておく & Dự Đoán 〜そうだ",
    description: "Khám phá thói quen chuẩn bị chu đáo trước mọi chuyến đi và phán đoán sự vật qua vẻ bề ngoài.",
    level: "N4",
    order: 4,
    xpReward: 40,
    exercises: [
      {
        type: "MULTIPLE_CHOICE",
        question: "Tính từ いい (Tốt) khi đi với そうだ (Trông có vẻ) sẽ biến đổi thành:",
        correctAnswer: "よさそうだ",
        points: 10,
        options: [
          { text: "よさそうだ", isCorrect: true },
          { text: "いいそうだ", isCorrect: false },
          { text: "いくそうだ", isCorrect: false },
          { text: "よいそうだ", isCorrect: false },
        ],
      },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// JLPT N4 SCENARIOS (SURVIVAL MODE)
// ─────────────────────────────────────────────────────────────────────────────
export const SCENARIOS_N4 = [
  {
    slug: "n4-baito-interview",
    title: "Phỏng Vấn Xin Việc Làm Thêm (Baito)",
    description: "Ứng tuyển vị trí nhân viên quán ăn tại Tokyo: Chào hỏi kính ngữ, trình bày kinh nghiệm và xác nhận lịch làm việc.",
    level: "N4",
    xpReward: 50,
    messages: [
      {
        order: 1,
        speaker: "店長 (Chủ quán)",
        japanese: "本日は面接にお越しいただきありがとうございます。まず自己紹介をお願いできますか？",
        romaji: "Honjitsu wa mensetsu ni okoshi itadaki arigatō gozaimasu. Mazu jikoshōkai o onegai dekimasu ka?",
        meaning: "Cảm ơn bạn hôm nay đã đến phỏng vấn. Trước hết bạn có thể tự giới thiệu đôi nét về bản thân không?",
      },
      {
        order: 2,
        speaker: "Bạn (Học viên)",
        japanese: "初めまして。ベトナムから参りましたナムと申します。日本の飲食文化を学びたくて応募いたしました。",
        romaji: "Hajimemashite. Betonamu kara mairimashita Namu to mōshimasu. Nihon no inshoku bunka o manabitakute ōbo itashimashita.",
        meaning: "Xin chào anh. Tôi là Nam đến từ Việt Nam. Vì rất muốn học hỏi văn hóa ẩm thực Nhật Bản nên tôi đã ứng tuyển vào vị trí này.",
      },
      {
        order: 3,
        speaker: "店長 (Chủ quán)",
        japanese: "週に何日くらい入れますか？",
        romaji: "Shū ni nannichi kurai hairemasu ka?",
        meaning: "Một tuần bạn có thể làm được khoảng mấy buổi?",
      },
    ],
    choices: [
      {
        optionText: "週に3日、平日の夕方と土曜日に働くことができます！",
        isIdeal: true,
        xpReward: 30,
      },
      {
        optionText: "いつでもいいですが、忙しい日は休みます。",
        isIdeal: false,
        xpReward: 5,
      },
    ],
  },
  {
    slug: "n4-apartment-leasing",
    title: "Thuê Nhà Trọ & Ký Hợp Đồng Bất Động Sản",
    description: "Trao đổi với công ty bất động sản Nhật Bản về tiền cọc (Shikikin), tiền lễ (Reikin) và quy định phân loại rác.",
    level: "N4",
    xpReward: 50,
    messages: [
      {
        order: 1,
        speaker: "不動産屋さん (Nhân viên BĐS)",
        japanese: "こちらの部屋は駅から徒歩5分で、敷金礼金もゼロとなっております。",
        romaji: "Kochira no heya wa eki kara toho go-fun de, shikikin reikin mo zero to natte orimasu.",
        meaning: "Căn phòng này cách ga 5 phút đi bộ, và tiền cọc cũng như tiền lễ đều bằng 0.",
      },
      {
        order: 2,
        speaker: "Bạn (Học viên)",
        japanese: "とても便利そうですね。契約の際に何が必要ですか？",
        romaji: "Totemo benri sō desu ne. Keiyaku no sai ni nani ga hitsuyō desu ka?",
        meaning: "Trông có vẻ rất tiện lợi. Khi làm hợp đồng thì tôi cần chuẩn bị những giấy tờ gì ạ?",
      },
    ],
    choices: [
      {
        optionText: "在留カードと銀行口座の書類を準備しておきます。",
        isIdeal: true,
        xpReward: 30,
      },
      {
        optionText: "何も持っていません。",
        isIdeal: false,
        xpReward: 5,
      },
    ],
  },
];
